<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <?php require("include/meta.phtml"); ?>
</head>
<body>
<div class="app">

    <header class="HRM__header">
        <div class="row">
            <div class="col-2 homepage__header-left">
                <a href="#" class="HRM__logo">
                    <i class="fa-solid fa-dove HRM__logo-text"> H R M</i>
                </a>
            </div>
            <div class="col-10 homepage__header-right">
                <p class="HRM__role-user-login">Vai trò: Nhân viên</p>
                <a class="HRM__login--redirect" href="#">Đăng nhập</a>
                <!-- <p class="HRM__logout--redirect">Đăng xuất</p> -->
            </div>
        </div>
    </header>

    <div class="HRM__container">
        <div class="row">
            <div class="col-2 homepage__container-left">
                <p class="HRM__funtions-list">Danh sách chức năng</p>
                
                <div class="HRM__functions-name">
                    <a class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-arrow-right-to-bracket"></i>
                        <p class="HRM__functions-name-items__name">Check In</p>
                    </a>
                    <a class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-arrow-right-to-bracket fa-flip-horizontal"></i>
                        <p class="HRM__functions-name-items__name">Check Out</p>
                    </a>
                    <a class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-clock"></i>
                        <p class="HRM__functions-name-items__name">Xin làm thêm giờ</p>
                    </a>
                    <a class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-bed-pulse"></i>
                        <p class="HRM__functions-name-items__name">Xin nghỉ phép</p>
                    </a>
                    <a class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-house"></i>
                        <p class="HRM__functions-name-items__name">Xin làm ở nhà</p>
                    </a>
                    <a class="HRM__functions-name-items HRM__functions-name-items__personalInfo">
                        <i class="HRM__functions-name-items__logo fa-solid fa-id-card"></i>
                        <p class="HRM__functions-name-items__name">Thông tin cá nhân</p>
                    </a>
                    <a class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-computer"></i>
                        <p class="HRM__functions-name-items__name">Yêu cầu thiết bị</p>
                    </a>
                    <a class="HRM__functions-name-items HRM__functions-name-items__companyActivity">
                        <i class="HRM__functions-name-items__logo fa-solid fa-calendar-days"></i>
                        <p class="HRM__functions-name-items__name">Hoạt động của công ty</p>
                    </a>
                </div>
            </div>
            <div class="col-10 homepage__container-right">
                <!-- ------------------------------------ -->
                <!-- ------------------------------------ -->
                <!-- BEGIN: Nội dung chính của trang web  -->
                <div>                    
                    <?php require($VIEW); ?>
                </div>
                <!-- END: Nội dung chính của trang web  -->
                <!-- ------------------------------------ -->
                <!-- ------------------------------------ -->
            </div>
        </div>
    </div>

</div>
<?php require("include/boostrap_scripts.phtml"); ?>

</body>
</html>