<?php
    if (session_status() === PHP_SESSION_NONE) {
        session_start();
    }
    if (!isset($_SESSION['username']))
    {
        header("Location: index.php");
    }
    function Logout()
    {
        unset($_SESSION['username']);
    }
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <?php require("include/meta.phtml"); ?>
</head>
<body>
<div class="app">

    <header class="HRM__header">
        <div class="row">
            <div class="col-2 homepage__header-left">
                <a href="index.php?action=home" class="HRM__logo">
                    <i class="fa-solid fa-dove HRM__logo-text"> H R M</i>
                </a>
            </div>
            <div class="col-10 homepage__header-right">
                <p class="HRM__role-user-login"><?php if (isset($_SESSION['roleName'])){echo 'Vai trò: ' . $_SESSION['roleName'];}?></p>
                <a href="index.php" class='HRM__logout--redirect'>Đăng xuất </a>
            </div>
        </div>
    </header>

    <div class="HRM__container">
        <div class="row">
            <div class="col-2 homepage__container-left">
                <p class="HRM__funtions-list">Danh sách chức năng</p>
                
                <div class="HRM__functions-name">
                    <!-- manager -->
                    <a class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-envelope"></i>
                        <p class="HRM__functions-name-items__name">Kiểm duyệt</p>
                    </a>
                    <a class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-arrow-right-to-bracket"></i>
                        <p class="HRM__functions-name-items__name">Check In/Out</p>
                    </a>
                    <a href="?action=requestListOT" class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-clock"></i>
                        <p class="HRM__functions-name-items__name">Xin làm thêm giờ</p>
                    </a>
                    <a href="?action=requestListOFF" class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-bed-pulse"></i>
                        <p class="HRM__functions-name-items__name">Xin nghỉ phép</p>
                    </a>
                    <a href="index.php?action=requestListWFH" class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-house"></i>
                        <p class="HRM__functions-name-items__name">Xin làm ở nhà</p>
                    </a>
                    <?php
                        $idEmployee = $_SESSION['idEmployee'];
                        echo "<a href='index.php?action=information&idEmployee={$idEmployee}' class='HRM__functions-name-items HRM__functions-name-items__personalInfo'>
                        <i class='HRM__functions-name-items__logo fa-solid fa-id-card'></i>
                        <p class='HRM__functions-name-items__name'>Thông tin cá nhân</p>
                        </a>";
                    ?>
                    
                    <!-- manager -->
                    <a class="HRM__functions-name-items HRM__functions-name-items__manageEmployee">
                        <i class="HRM__functions-name-items__logo fa-solid fa-id-card"></i>
                        <p class="HRM__functions-name-items__name">Quản lý nhân viên</p>
                    </a>
                    <a class="HRM__functions-name-items">
                        <i class="HRM__functions-name-items__logo fa-solid fa-computer"></i>
                        <p class="HRM__functions-name-items__name">Yêu cầu thiết bị</p>
                    </a>
                    <a class="HRM__functions-name-items HRM__functions-name-items__companyActivity">
                        <i class="HRM__functions-name-items__logo fa-solid fa-calendar-days"></i>
                        <p class="HRM__functions-name-items__name">Hoạt động công ty</p>
                    </a>
                </div>
            </div>
            <div class="col-10 homepage__container-right">
                <!-- ------------------------------------ -->
                <!-- ------------------------------------ -->
                <!-- BEGIN: Nội dung chính của trang web  -->
                <div>                    
                    <?php require($VIEW); ?>
                </div>
                <!-- END: Nội dung chính của trang web  -->
                <!-- ------------------------------------ -->
                <!-- ------------------------------------ -->
            </div>
        </div>
    </div>

</div>
<?php require("include/boostrap_scripts.phtml"); ?>
<?php require("js/role.phtml"); ?>

</body>
</html>