<script>
    var statusRequests = document.querySelectorAll(".censorship__container-content-row-element-status-name");
    statusRequests.forEach(index => {
        var statusValue = index.innerText;
        if(statusValue == "Chấp thuận"){
            index.style.cssText += "background-color: var(--green-color);color: var(--white-color);";
        }
        else if(statusValue == "Chưa xét duyệt"){
            index.style.cssText += "background-color: var(--lightgreen-color);color: var(--green-color);";
        }
        else{
            index.style.cssText += "background-color: var(--lightred-color);color: var(--red-color);";
        }
    })

    function filterTypeRequest(){
        var type = document.getElementById("typeRequest").value;
        var status = document.getElementById("requestStatus").value;
        var url ="index.php?action=censorship&idCensorship="+type+status;
        if(url != ''){
            window.location=url;
        }
        return false;
    }
</script>