
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet"  type="text/css" href="assets/fonts/fontawesome-free-6.1.1-web/css/all.min.css">
<link rel="stylesheet"  type="text/css" href="assets/css/base.css">   
<link rel="stylesheet"  type="text/css" href="assets/css/employee_OFF.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_OT.css">
<link rel="stylesheet"  type="text/css" href="assets/css/homepage.css">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

