
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet"  type="text/css" href="assets/fonts/fontawesome-free-6.1.1-web/css/all.min.css">
<link rel="stylesheet"  type="text/css" href="assets/css/base.css">   
<link rel="stylesheet"  type="text/css" href="assets/css/employee_OFF.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_DR.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_A.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_OT.css">
<link rel="stylesheet"  type="text/css" href="assets/css/ITmanager_DR.css">
<link rel="stylesheet"  type="text/css" href="assets/css/ITmanager_formDR.css">
<link rel="stylesheet"  type="text/css" href="assets/css/president_DR.css">
<link rel="stylesheet"  type="text/css" href="assets/css/president_formDR.css">
<link rel="stylesheet"  type="text/css" href="assets/css/homepage.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_information.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_tasks.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_taskdetail.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_list.css">
<link rel="stylesheet"  type="text/css" href="assets/css/censorship.css">
<link rel="stylesheet"  type="text/css" href="assets/css/censorship_detail.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_loginlogout.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_WFH.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_checkincheckout.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_checkincheckout_history.css">
<link rel="stylesheet"  type="text/css" href="assets/css/employee_checkout_late.css">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

