<div class="row">
    <div class="censorship__container-title">
        <div class="censorship__container-title-first">
            <div class="censorship__container-title-first__name">
                <spa>Danh sách để xuất</spa>
            </div>
            <div class="censorship__container-title-first__filter">
                <label>Loại đề xuất:</label>
                <select class="censorship__container-title-first__filter-list">
                    <option value="all">Tất cả</option>
                    <option value="all">Yêu cầu nghỉ phép</option>
                    <option value="all">Yêu cầu OT</option>
                    <option value="all">Yêu cầu checkout bù</option>
                </select>
            </div>
        </div>
        <div class="censorship__container-title-nav">
            <div class="censorship__container-title-nav-content-link">
                <a class="censorship__container-title-nav-content-link-value">TẤT CẢ</a>
            </div>
            <div class="censorship__container-title-nav-content-link">
                <a class="censorship__container-title-nav-content-link-value">ĐANG CHỜ DUYỆT</a>
            </div>
            <div class="censorship__container-title-nav-content-link">
                <a class="censorship__container-title-nav-content-link-value">ĐÃ PHÊ DUYỆT</a>
            </div>
            <div class="censorship__container-title-nav-content-link">
                <a class="censorship__container-title-nav-content-link-value">ĐÃ TỪ CHỐI</a>
            </div>
        </div>
    </div>
    <div class="censorship__container-content">
        <div class="censorship__container-content-row">
            <div class="censorship__container-content-row-element">
                <div class="col-8 censorship__container-content-row-element-index">
                    <span class="censorship__container-content-row-element-index-name">Tên yêu cầu</span>
                    <span class="censorship__container-content-row-element-index-employee">Nhân viên</span>
                    <span class="censorship__container-content-row-element-index-reason">Lý do</span>
                </div>
                <div class="col-2 censorship__container-content-row-element-type">
                    <div class="censorship__container-content-row-element-type-name">
                        <span>Yêu cầu nghỉ phép</span>
                    </div>
                </div>
                <div class="col-2 censorship__container-content-row-element-status">
                    <div class="censorship__container-content-row-element-status-name">
                        <span>Chấp thuận</span>
                    </div>
                </div>
                <div class="censorship__container-content-row-element-date">
                    <div class="censorship__container-content-row-element-date-name">
                        <span>Date</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="censorship__container-content-row">
            <div class="censorship__container-content-row-element">
                <div class="col-8 censorship__container-content-row-element-index">
                    <span class="censorship__container-content-row-element-index-name">Tên yêu cầu</span>
                    <span class="censorship__container-content-row-element-index-employee">Nhân viên</span>
                    <span class="censorship__container-content-row-element-index-reason">Lý do</span>
                </div>
                <div class="col-2 censorship__container-content-row-element-type">
                    <div class="censorship__container-content-row-element-type-name">
                        <span>Yêu cầu checkout bù</span>
                    </div>
                </div>
                <div class="col-2 censorship__container-content-row-element-status">
                    <div class="censorship__container-content-row-element-status-name">
                        <span>Từ chối</span>
                    </div>
                </div>
                <div class="censorship__container-content-row-element-date">
                    <div class="censorship__container-content-row-element-date-name">
                        <span>Date</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="censorship__container-content-row">
            <div class="censorship__container-content-row-element">
                <div class="col-8 censorship__container-content-row-element-index">
                    <span class="censorship__container-content-row-element-index-name">Tên yêu cầu</span>
                    <span class="censorship__container-content-row-element-index-employee">Nhân viên</span>
                    <span class="censorship__container-content-row-element-index-reason">Lý do</span>
                </div>
                <div class="col-2 censorship__container-content-row-element-type">
                    <div class="censorship__container-content-row-element-type-name">
                        <span>Yêu cầu OT</span>
                    </div>
                </div>
                <div class="col-2 censorship__container-content-row-element-status">
                    <div class="censorship__container-content-row-element-status-name">
                        <span>Chờ duyệt</span>
                    </div>
                </div>
                <div class="censorship__container-content-row-element-date">
                    <div class="censorship__container-content-row-element-date-name">
                        <span>Date</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<?php require("js/censorship.phtml"); ?>