<div class="censorship-detail__header">
    <div class="row">
        <div class="censorship-detail__header_nav">
            <a class="censorship-detail__header-nav-item">
                <i class="censorship-detail__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="censorship-detail__header-nav-item-name">Kiểm duyệt</p>
            </a>
        </div>
    </div>
</div>
<div class="censorship-detail__container">
    <div class="row">
        <div class="censorship-detail__container-title">
            <div class="censorship-detail__container-title-first">
                <div class="censorship-detail__container-title-first__name">
                    <spa>Danh sách để xuất</spa>
                </div>
                <div class="censorship-detail__container-title-first__filter">
                    <label>Loại đề xuất:</label>
                    <select class="censorship-detail__container-title-first__filter-list">
                        <option value="all">Tất cả</option>
                        <option value="all">Yêu cầu nghỉ phép</option>
                        <option value="all">Yêu cầu OT</option>
                        <option value="all">Yêu cầu checkout bù</option>
                    </select>
                </div>
            </div>
            <div class="censorship-detail__container-title-nav">
                <div class="censorship-detail__container-title-nav-content-link">
                    <a class="censorship-detail__container-title-nav-content-link-value">TẤT CẢ</a>
                </div>
                <div class="censorship-detail__container-title-nav-content-link">
                    <a class="censorship-detail__container-title-nav-content-link-value">ĐANG CHỜ DUYỆT</a>
                </div>
                <div class="censorship-detail__container-title-nav-content-link">
                    <a class="censorship-detail__container-title-nav-content-link-value">ĐÃ PHÊ DUYỆT</a>
                </div>
                <div class="censorship-detail__container-title-nav-content-link">
                    <a class="censorship-detail__container-title-nav-content-link-value">ĐÃ TỪ CHỐI</a>
                </div>
            </div>
        </div>
        <div class="censorship-detail__container-content">
            <div class="censorship-detail__container-content-request-list">
                <div class="censorship-detail__container-content-request-list-item" style="background-color: var(--secondary-color);">
                    <a class="censorship-detail__container-content-request-list-item-element">
                        <div class="censorship-detail__container-content-request-list-item-element__title">
                            <span class="censorship-detail__container-content-request-list-item-element__title-name" style="color: var(--white-color);">Yêu cầu nghỉ phép ngày 20/05</span>
                        </div>
                        <div class="censorship-detail__container-content-request-list-item-element__description">
                            <span class="censorship-detail__container-content-request-list-item-element__description-name" style="color: var(--white-color);">Nhân viên a, asda</span>
                        </div>
                    </a>
                </div>
                <div class="censorship-detail__container-content-request-list-item">
                    <a class="censorship-detail__container-content-request-list-item-element">
                        <div class="censorship-detail__container-content-request-list-item-element__title">
                            <span class="censorship-detail__container-content-request-list-item-element__title-name">Yêu cầu nghỉ phép ngày 20/05</span>
                        </div>
                        <div class="censorship-detail__container-content-request-list-item-element__description">
                            <span class="censorship-detail__container-content-request-list-item-element__description-name">Nhân viên a, asda</span>
                        </div>
                    </a>
                </div>
                <div class="censorship-detail__container-content-request-list-item">
                    <a class="censorship-detail__container-content-request-list-item-element">
                        <div class="censorship-detail__container-content-request-list-item-element__title">
                            <span class="censorship-detail__container-content-request-list-item-element__title-name">Yêu cầu nghỉ phép ngày 20/05</span>
                        </div>
                        <div class="censorship-detail__container-content-request-list-item-element__description">
                            <span class="censorship-detail__container-content-request-list-item-element__description-name">Nhân viên a, asda</span>
                        </div>
                    </a>
                </div>
                <div class="censorship-detail__container-content-request-list-item">
                    <a class="censorship-detail__container-content-request-list-item-element">
                        <div class="censorship-detail__container-content-request-list-item-element__title">
                            <span class="censorship-detail__container-content-request-list-item-element__title-name">Yêu cầu nghỉ phép ngày 20/05</span>
                        </div>
                        <div class="censorship-detail__container-content-request-list-item-element__description">
                            <span class="censorship-detail__container-content-request-list-item-element__description-name">Nhân viên a, asda</span>
                        </div>
                    </a>
                </div>
                <div class="censorship-detail__container-content-request-list-item">
                    <a class="censorship-detail__container-content-request-list-item-element">
                        <div class="censorship-detail__container-content-request-list-item-element__title">
                            <span class="censorship-detail__container-content-request-list-item-element__title-name">Yêu cầu nghỉ phép ngày 20/05</span>
                        </div>
                        <div class="censorship-detail__container-content-request-list-item-element__description">
                            <span class="censorship-detail__container-content-request-list-item-element__description-name">Nhân viên a, asda</span>
                        </div>
                    </a>
                </div>
            </div>
            <div class="censorship-detail__container-content-request-detail">
                <div class="censorship-detail__container-content-request-detail-title">
                    <div class="censorship-detail__container-content-request-detail-title-name">
                        <span>Yêu cầu nghỉ phép</span>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-title-status">
                        <span>Trạng thái: </span>
                        <span style="color: var(--secondary-color);">Đang chờ duyệt</span>
                    </div>
                </div>
                <div class="censorship-detail__container-content-request-detail-btn">
                    <div class="censorship-detail__container-content-request-detail-btn-list">
                        <div class="censorship-detail__container-content-request-detail-btn-list-item">
                            <div class="censorship-detail__container-content-request-detail-btn-list-item-element">
                                <input type="button" class="censorship-detail__container-content-request-detail-btn-list-item-element__agree" value="Chấp thuận">
                            </div>
                        </div>
                        <div class="censorship-detail__container-content-request-detail-btn-list-item">
                            <div class="censorship-detail__container-content-request-detail-btn-list-item-element">
                                <input type="button" class="censorship-detail__container-content-request-detail-btn-list-item-element__disagree" value="Từ chối">
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-btn-title">
                        <span class="censorship-detail__container-content-request-detail-btn-title-name">THÔNG TIN ĐỀ XUẤT</span>
                    </div>
                </div>
                <div class="censorship-detail__container-content-request-detail-request">
                    <div class="censorship-detail__container-content-request-detail-request-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-item-left">
                                <div class="censorship-detail__container-content-request-detail-request-item-icon">
                                    <i class="fa-solid fa-file-lines"></i>
                                </div>
                                <div class="censorship-detail__container-content-request-detail-request-item-title">
                                    <span>Loại yêu cầu</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-item-right">
                                <span class="censorship-detail__container-content-request-detail-request-item-right-value">Xin nghỉ phép</span>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-item-left">
                                <div class="censorship-detail__container-content-request-detail-request-item-icon">
                                    <i class="fa-solid fa-circle-user"></i>
                                </div>
                                <div class="censorship-detail__container-content-request-detail-request-item-title">
                                    <span>Người tạo</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-item-right">
                                <span class="censorship-detail__container-content-request-detail-request-item-right-value">Nguyễn Quang Pháp</span>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-item-left">
                                <div class="censorship__container-content-request-detail-request-item-icon">
                                    <i class="fa-solid fa-building"></i>
                                </div>
                                <div class="censorship-detail__container-content-request-detail-request-item-title">
                                    <span>Phòng ban</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-item-right">
                                <span class="censorship-detail__container-content-request-detail-request-item-right-value">Phòng IT</span>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-item-left">
                                <div class="censorship-detail__container-content-request-detail-request-item-icon">
                                    <i class="fa-solid fa-calendar-days"></i>
                                </div>
                                <div class="censorship-detail__container-content-request-detail-request-item-title">
                                    <span>Thời gian tạo</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-item-right">
                                <span class="censorship-detail__container-content-request-detail-request-item-right-value">20/07/2022</span>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-item-left">
                                <div class="censorship-detail__container-content-request-detail-request-item-icon">
                                    <i class="fa-solid fa-window-maximize"></i>
                                </div>
                                <div class="censorship-detail__container-content-request-detail-request-item-title">
                                    <span>Lý do</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-item-right">
                                <span class="censorship-detail__container-content-request-detail-request-item-right-value">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Pariatur distinctio quod nisi, molestiae eligendi hic itaque consequatur minima iste temporibus soluta.</span>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-title">
                        <span class="censorship-detail__container-content-request-detail-request-title-name">THÔNG TIN KHÁC (MẪU ĐỀ XUẤT KHÁC)</span>
                    </div>
                </div>
                <div class="censorship-detail__container-content-request-detail-request-other">
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Ngày làm thêm giờ</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-result-value">20/07/2022</span>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Số giờ dự kiến</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-result-value">4</span>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Ngày xin nghỉ</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-result-value">20/07/2022</span>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Số ngày nghỉ</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-result-value">1</span>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Ghi chú nghỉ</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-result-value">Sáng</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="censorship-detail__container-content-request-manager">
                <div class="censorship-detail__container-content-request-manager-element">
                    <div class="censorship-detail__container-content-request-manager-title">
                        <span class="censorship-detail__container-content-request-manager-title-name">NGƯỜI KIỂM DUYỆT</span>
                    </div>
                    <div class="censorship-detail__container-content-request-manager-member">
                        <div class="censorship-detail__container-content-request-manager-member-image">
                            <div class="circular--landscape-manager">
                                <img src="assets/img/profile.jpg" alt="Avatar" />
                            </div>
                        </div>
                        <div class="censorship-detail__container-content-request-manager-member-info">
                            <div class="censorship-detail__container-content-request-manager-member-info-name">
                                <span class="censorship-detail__container-content-request-manager-member-info-name__value">Nguyễn Quang Pháp</span>
                            </div>
                            <div class="censorship-detail__container-content-request-manager-member-info-position">
                                <span class="censorship-detail__container-content-request-manager-member-info-position__value">Trưởng phòng</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>