<div class="censorship-detail__header">
    <div class="row">
        <div class="censorship-detail__header_nav">
            <a class="censorship-detail__header-nav-item">
                <i class="censorship-detail__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="censorship-detail__header-nav-item-name">Kiểm duyệt</p>
            </a>
        </div>
    </div>
</div>
<div class="censorship-detail__container">
    <div class="row">
        <div class="censorship-detail__container-title">
            <div class="censorship-detail__container-title-first">
                <div class="censorship-detail__container-title-first__name">
                    <span>Chi tiết đề xuất</span>
                </div>
                <div class="censorship-detail__container-title-first__filter">
                    <label>Loại đề xuất:</label>
                    <select class="censorship-detail__container-title-first__filter-list" id="typeRequest" onchange="filterDetailTypeRequest();">
                    <?php
                        $idCensorship = $_REQUEST["idCensorship"];
                        $typeRequest = $_REQUEST["typeRequest"];

                        if(strcmp($typeRequest, "all") == 0){
                            echo "<option value='{$idCensorship}&page=1&typeRequest=all&idRequest=0' selected>Tất cả</option>";
                        }
                        else{
                            echo "<option value='{$idCensorship}&page=1&typeRequest=all&idRequest=0'>Tất cả</option>";
                        }

                        if(strcmp($typeRequest, "off") == 0){
                            echo "<option value='{$idCensorship}&page=1&typeRequest=off&idRequest=0' selected>Yêu cầu nghỉ phép</option>";
                        }
                        else{
                            echo "<option value='{$idCensorship}&page=1&typeRequest=off&idRequest=0'>Yêu cầu nghỉ phép</option>";
                        }

                        if(strcmp($typeRequest, "ot") == 0){
                            echo "<option value='{$idCensorship}&page=1&typeRequest=ot&idRequest=0' selected>Yêu cầu OT</option>";
                        }
                        else{
                            echo "<option value='{$idCensorship}&page=1&typeRequest=ot&idRequest=0'>Yêu cầu OT</option>";
                        }

                        if(strcmp($typeRequest, "home") == 0){
                            echo "<option value='{$idCensorship}&page=1&typeRequest=home&idRequest=0' selected>Yêu cầu làm việc tại nhà</option>";
                        }
                        else{
                            echo "<option value='{$idCensorship}&page=1&typeRequest=home&idRequest=0'>Yêu cầu làm việc tại nhà</option>";
                        }

                        if(strcmp($typeRequest, "checkout") == 0){
                            echo "<option value='{$idCensorship}&page=1&typeRequest=checkout&idRequest=0' selected>Yêu cầu checkout bù</option>";
                        }
                        else{
                            echo "<option value='{$idCensorship}&page=1&typeRequest=checkout&idRequest=0'>Yêu cầu checkout bù</option>";
                        }
                    ?>
                    </select>
                </div>
                <div class="censorship__container-title-first__filter">
                    <label>Trạng thái:</label>
                    <select class="censorship__container-title-first__filter-list" id="requestStatus" onchange="filterDetailTypeRequest();">
                    <?php
                        $requestStatus = $_REQUEST["requestStatus"];
                        if(strcmp($requestStatus, "all") == 0){
                            echo "<option value='&requestStatus=all' selected>Tất cả</option>";
                        }
                        else{
                            echo "<option value='&requestStatus=all'>Tất cả</option>";
                        }

                        if(strcmp($requestStatus, "unconfimred") == 0){
                            echo "<option value='&requestStatus=unconfimred' selected>Chưa xét duyệt</option>";
                        }
                        else{
                            echo "<option value='&requestStatus=unconfimred'>Chưa xét duyệt</option>";
                        }

                        if(strcmp($requestStatus, "confimred") == 0){
                            echo "<option value='&requestStatus=confimred' selected>Chấp thuận</option>";
                        }
                        else{
                            echo "<option value='&requestStatus=confimred'>Chấp thuận</option>";
                        }

                        if(strcmp($requestStatus, "reject") == 0){
                            echo "<option value='&requestStatus=reject' selected>Từ chối</option>";
                        }
                        else{
                            echo "<option value='&requestStatus=reject'>Từ chối</option>";
                        }
                    ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="censorship-detail__container-content">
            <div class="censorship-detail__container-content-request-list">
                <?php
                    $self = $_SERVER['PHP_SELF'];
                    $currentPage = 1;
                    if (isset($_REQUEST["page"]))
                        $currentPage = $_REQUEST["page"];
                    $n = count($data['listRequest']);
                    $i = 0;
                    $idCensorship = $_REQUEST["idCensorship"];
                    $page = $_REQUEST["page"];
                    $typeRequest = $_REQUEST["typeRequest"];
                    
                    while ($i < $n) {
                        $fullName = $data['listRequest'][$i]['employeeFirstName']." ".$data['listRequest'][$i]['employeeLastName'];
                        if((int)$data['detailRequest']['id'] == (int)$data['listRequest'][$i]['id']){
                            echo "<div class='censorship-detail__container-content-request-list-item' style='background-color: var(--secondary-color);'>
                                    <a href='index.php?action=censorshipdetail&idCensorship={$idCensorship}&page={$page}&typeRequest={$typeRequest}&idRequest={$data['listRequest'][$i]['id']}' class='censorship-detail__container-content-request-list-item-element'>
                                        <div class='censorship-detail__container-content-request-list-item-element__title'>
                                            <span class='censorship-detail__container-content-request-list-item-element__title-name' style='color: var(--white-color);'>{$data['listRequest'][$i]['requestName']}</span>
                                        </div>
                                        <div class='censorship-detail__container-content-request-list-item-element__description'>
                                            <span class='censorship-detail__container-content-request-list-item-element__description-name' style='color: var(--white-color);'>{$fullName}, {$data['listRequest'][$i]['requestStatus']}</span>
                                        </div>
                                    </a>
                                </div>";
                        }
                        else{
                            echo "<div class='censorship-detail__container-content-request-list-item'>
                                    <a href='index.php?action=censorshipdetail&idCensorship={$idCensorship}&page={$page}&typeRequest={$typeRequest}&idRequest={$data['listRequest'][$i]['id']}' class='censorship-detail__container-content-request-list-item-element'>
                                        <div class='censorship-detail__container-content-request-list-item-element__title'>
                                            <span class='censorship-detail__container-content-request-list-item-element__title-name'>{$data['listRequest'][$i]['requestName']}</span>
                                        </div>
                                        <div class='censorship-detail__container-content-request-list-item-element__description'>
                                            <span class='censorship-detail__container-content-request-list-item-element__description-name'>{$fullName}, {$data['listRequest'][$i]['requestStatus']}</span>
                                        </div>
                                    </a>
                                </div>";
                        }
                        $i += 1;
                    }
                ?>
                <div class="information__container-right__content-list-paging">
                    <div class="information__container-right__content-list-paging-element">
                        <?php
                            $requestStatus = $_REQUEST["requestStatus"];
                            if ($currentPage > 1)
                            {
                                $page = $currentPage - 1;
                                
                                $prev = "<a class='paging-data' href='$self?action=censorshipdetail&idCensorship={$idCensorship}&page={$page}&typeRequest={$typeRequest}&idRequest=0&requestStatus=$requestStatus'><</a>     ";
                            }
                            else
                            {
                                
                                $prev = "<a class='paging-data' href='$self?action=censorshipdetail&idCensorship={$idCensorship}&page=1&typeRequest={$typeRequest}&idRequest=0&requestStatus=$requestStatus'><</a>     ";
                            }


                            $page = $currentPage + 1;
                            $next = "     <a class='paging-data' href='$self?action=censorshipdetail&idCensorship={$idCensorship}&page={$page}&typeRequest={$typeRequest}&idRequest=0&requestStatus=$requestStatus'>></a>";

                            echo $prev.$currentPage.$next;
                        ?>
                    </div>
                </div>
            </div>
            <div class="censorship-detail__container-content-request-detail">
                <div class="censorship-detail__container-content-request-detail-title">
                    <div class="censorship-detail__container-content-request-detail-title-name">
                        <?php
                            $currentPage = 1;
                            if (isset($_REQUEST["page"]))
                                $currentPage = $_REQUEST["page"];
                            echo "<span>{$data['detailRequest']['requestName']}</span>
                            <input type='hidden' id='idRequest' value='{$data['detailRequest']['id']}'>
                            <input type='hidden' id='idCensorship' value='{$idCensorship}'>
                            <input type='hidden' id='page' value='{$currentPage}'>
                            <input type='hidden' id='typeRequest' value='{$typeRequest}'>";
                        ?>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-title-status">
                        <span>Trạng thái: </span>
                        <?php
                            echo "<span class='censorship-detail__container-content-request-detail-title-status-value' >{$data['detailRequest']['requestStatus']}</span>";
                        ?>
                        
                    </div>
                </div>
                <div class="censorship-detail__container-content-request-detail-btn">
                    <div class="censorship-detail__container-content-request-detail-btn-list">
                        <div class="censorship-detail__container-content-request-detail-btn-list-item">
                            <div class="censorship-detail__container-content-request-detail-btn-list-item-element">
                                <input type="button" class="censorship-detail__container-content-request-detail-btn-list-item-element__agree" value="Chấp thuận" onclick="updateStatusRequest('Chấp thuận');">
                            </div>
                        </div>
                        <div class="censorship-detail__container-content-request-detail-btn-list-item">
                            <div class="censorship-detail__container-content-request-detail-btn-list-item-element">
                                <input type="button" class="censorship-detail__container-content-request-detail-btn-list-item-element__disagree" value="Từ chối" onclick="clickBtnReject();">
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-btn-reason-reject" >
                        <form id="click-btn-reject"></form>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-btn-title">
                        <span class="censorship-detail__container-content-request-detail-btn-title-name">THÔNG TIN ĐỀ XUẤT</span>
                    </div>
                </div>
                <div class="censorship-detail__container-content-request-detail-request">
                    <div class="censorship-detail__container-content-request-detail-request-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-item-left">
                                <div class="censorship-detail__container-content-request-detail-request-item-icon">
                                    <i class="fa-solid fa-file-lines"></i>
                                </div>
                                <div class="censorship-detail__container-content-request-detail-request-item-title">
                                    <span>Loại yêu cầu</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-item-right" >
                                <?php
                                    echo "<span id='typeName' class='censorship-detail__container-content-request-detail-request-item-right-value'>{$data['detailRequest']['typeName']}</span>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-item-left">
                                <div class="censorship-detail__container-content-request-detail-request-item-icon">
                                    <i class="fa-solid fa-circle-user"></i>
                                </div>
                                <div class="censorship-detail__container-content-request-detail-request-item-title">
                                    <span>Người tạo</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-item-right">
                                <?php
                                    $fullName = $data['detailRequest']['employeeFirstName']." ".$data['detailRequest']['employeeLastName'];
                                    echo "<span class='censorship-detail__container-content-request-detail-request-item-right-value'>{$fullName}</span>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-item-left">
                                <div class="censorship-detail__container-content-request-detail-request-item-icon">
                                    <i class="fa-solid fa-calendar-days"></i>
                                </div>
                                <div class="censorship-detail__container-content-request-detail-request-item-title">
                                    <span>Thời gian tạo</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-item-right">
                                <?php
                                    $date = date('d-m-Y',strtotime($data['detailRequest']['requestDate']));
                                    echo "<span class='censorship-detail__container-content-request-detail-request-item-right-value'>{$date}</span>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-item-left">
                                <div class="censorship-detail__container-content-request-detail-request-item-icon">
                                    <i class="fa-solid fa-window-maximize"></i>
                                </div>
                                <div class="censorship-detail__container-content-request-detail-request-item-title">
                                    <span>Lý do</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-item-right">
                                <?php
                                    echo "<span class='censorship-detail__container-content-request-detail-request-item-right-value'>{$data['detailRequest']['reason']}</span>";
                                ?>
                                
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-item" >
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-item-left" >
                                <div class="censorship-detail__container-content-request-detail-request-item-icon" style="color:var(--red-color) !important;">
                                    <i class="fa-solid fa-window-maximize"></i>
                                </div>
                                <div class="censorship-detail__container-content-request-detail-request-item-title" style="color:var(--red-color) !important;">
                                    <span>Lý do từ chối</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-item-right">
                                <?php
                                    echo "<span  style='color:var(--red-color) !important;' class='censorship-detail__container-content-request-detail-request-item-right-value'>{$data['detailRequest']['requestRejectReason']}</span>";
                                ?>
                                
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-title">
                        <span class="censorship-detail__container-content-request-detail-request-title-name">THÔNG TIN KHÁC (MẪU ĐỀ XUẤT KHÁC)</span>
                    </div>
                </div>
                <div class="censorship-detail__container-content-request-detail-request-other">
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Ngày làm thêm giờ</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <?php
                                    $date = date('d-m-Y',strtotime($data['detailRequest']['dayOT']));
                                    echo "<span class='censorship-detail__container-content-request-detail-request-other-item-result-value'>{$date}</span>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Số giờ dự kiến</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <?php
                                    echo "<span class='censorship-detail__container-content-request-detail-request-other-item-result-value'>{$data['detailRequest']['hourOT']}</span>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Ngày xin nghỉ</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <?php
                                    $date = date('d-m-Y',strtotime($data['detailRequest']['startDayOFF']));
                                    echo "<span class='censorship-detail__container-content-request-detail-request-other-item-result-value'>{$date}</span>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Số ngày nghỉ</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <?php
                                    echo "<span class='censorship-detail__container-content-request-detail-request-other-item-result-value'>{$data['detailRequest']['numberDayOFF']}</span>";
                                ?>
                                
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Ghi chú nghỉ</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <?php
                                    echo "<span class='censorship-detail__container-content-request-detail-request-other-item-result-value'>{$data['detailRequest']['noteDayOFF']}</span>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Từ ngày</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <?php
                                    $date = date('d-m-Y',strtotime($data['detailRequest']['startDayWFH']));
                                    echo "<span class='censorship-detail__container-content-request-detail-request-other-item-result-value'>{$date}</span>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Đến ngày</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <?php
                                    $date = date('d-m-Y',strtotime($data['detailRequest']['endDayWFH']));
                                    echo "<span class='censorship-detail__container-content-request-detail-request-other-item-result-value'>{$date}</span>";
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="censorship-detail__container-content-request-detail-request-other-item">
                        <div class="col-4">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-title">
                                <span class="censorship-detail__container-content-request-detail-request-other-item-title-value">Ngày xin checkout</span>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="censorship-detail__container-content-request-detail-request-other-item-result">
                                <?php
                                    $date = date('d-m-Y',strtotime($data['detailRequest']['checkoutDate']));
                                    echo "<span class='censorship-detail__container-content-request-detail-request-other-item-result-value'>{$date}</span>";
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="censorship-detail__container-content-request-manager">
                <div class="censorship-detail__container-content-request-manager-element">
                    <div class="censorship-detail__container-content-request-manager-title">
                        <span class="censorship-detail__container-content-request-manager-title-name">NGƯỜI KIỂM DUYỆT</span>
                    </div>
                    <div class="censorship-detail__container-content-request-manager-member">
                        <div class="censorship-detail__container-content-request-manager-member-image">
                            <div class="circular--landscape-manager">
                                <img src="assets/img/profile.png" alt="Avatar" />
                            </div>
                        </div>
                        <div class="censorship-detail__container-content-request-manager-member-info">
                            <div class="censorship-detail__container-content-request-manager-member-info-name">
                                <?php
                                    $censorFullName = $data['detailRequest']['censorFirstName']." ".$data['detailRequest']['censorLastName'];
                                    echo "<span class='censorship-detail__container-content-request-manager-member-info-name__value'>{$censorFullName}</span>";
                                ?>
                                
                            </div>
                            <div class="censorship-detail__container-content-request-manager-member-info-position">
                                <?php
                                    echo "<span class='censorship-detail__container-content-request-manager-member-info-position__value'>{$data['detailRequest']['positionCensor']}</span>";
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php require("js/censorship_detail.phtml"); ?>