<div class="row">
    <div class="col-10 Checkin__group">
        <p class="Checkin__group-title">Chấm công</p>
    </div>
</div>
<div class="Checkin">
    <div class="row">
        <span class="Checkin__information">Thông tin chấm công</span>
        <span class="Checkin__information-detail">Thực hiện đầy đủ các yêu cầu để tiến hành chấm công</span>
    </div>
    <div class="row Checkin__request">
        <div class="col-6">
            <div class="Checkin__request-session">
                <span class="Checkin__request-session-name">Nơi làm việc *</span>
            </div>
            <span class="Checkin__request-session-name-detail">Công ty FPT</span>
        </div>
        <div class="col-4">
            <div class="Checkin__request-image">
                <span class="Checkin__request-image-name">Ảnh chụp tại nơi làm việc *</span>
            </div>
            <input class="Checkin__request-image-input" type="file" accept="image/*">
        </div>
        <div class="col-2 Checkin__button">
            <form action="index.php?action=addCheckin" method="POST">
                <button onclick="checkCheckinTimeValid();" type="submit" class="btn btn-success Checkin__button-submit">Check in</p>
            </form>
        </div>
        <div class="col-2 Checkout__button">
            <form action="index.php?action=addCheckout" method="POST">
                <button onclick="checkCheckoutTimeValid();" type="submit" class="btn btn-success Checkout__button-submit">Check out</p>
            </form>
        </div>
    </div>
</div>


<style>
.Checkout__button {
    width: 130px;
    height: 40px;
    display: none;
    padding-top: 20px;
}

.Checkout__button-submit {
    width: 100px;
    height: 45px;
}
</style>

<?php require("js/checkincheckout.phtml"); ?>