<div class="row CheckinHistory">
    <div class="col-10 CheckinHistory__group">
        <p class="CheckinHistory__group-title">Lịch sử chấm công</p>
    </div>
    <div class="col-2 CheckinHistory__group">
        <a style="text-decoration: none; color:white" href="index.php?action=checkin"><button type="button" class="btn btn-success CheckinHistory__group-btn-newcheckin">+ Chấm công</p></a>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
        <th scope="col">Ngày</th>
        <th scope="col">Giờ bắt đầu</th>
        <th scope="col">Giờ kết thúc</th>
        <th scope="col">Đánh giá</th>
        </tr>
    </thead>
    <tbody>
        <tr>
        <th scope="row">1</th>
        <td>07:30</td>
        <td>16:30</td>
        <td>Làm đủ giờ</td>
        </tr>
        <tr>
        <th scope="row">2</th>
        <td>07:30</td>
        <td>16:00</td>
        <td>Làm thiếu giờ</td>
        </tr>
        <tr>
        <th scope="row">3</th>
        <td>07:30</td>
        <td>Không Check-out</td>
        <td>Không tính ngày làm việc</td>
        </tr>
        <tr>
        <th scope="row">3</th>
        <td>Không Check-in</td>
        <td>Không Check-out</td>
        <td>Không tính ngày làm việc</td>
        </tr>
    </tbody>
</table>
<div class="row">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
            <a class="page-link" href="#">Next</a>
            </li>
        </ul>
        </nav>
</div>