<div class="manager__header">
    <div class="row">
        <div class="manager__header_nav">
            <a class="manager__header-nav-item">
                <i class="manager__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="manager__header-nav-item-name">Quản lý nhân viên</p>
            </a>
        </div>
    </div>
</div>
<div class="manager__container">
    <div class="row">
        <div class="manager__container-title">
            <div class="manager__container-title-first">
                <div class="manager__container-title-first__name">
                    <spa>Danh sách nhân viên</spa>
                </div>
            </div>
        </div>
        <div class="manager__container-list">
            <div class="manager__container-list-title">
                <div class="manager__container-list-title-name">
                    <span>NHÂN VIÊN</span>
                </div>
                <div class="manager__container-list-title-code">
                    <span>MÃ NV</span>
                </div>
                <div class="manager__container-list-title-department">
                    <span>PHÒNG BAN</span>
                </div>
                <div class="manager__container-list-title-position">
                    <span>CHỨC VỤ</span>
                </div>
            </div>
            <div class="manager__container-list-employee">
                <div class="manager__container-list-employee-item">
                    <a class="manager__container-list-employee-item-link">
                        <div class="manager__container-list-employee-item-fullname">
                            <div class="manager__container-list-employee-item-fullname-image">
                                <div class="circular--landscape-list-employee">
                                    <img src="assets/img/profile.jpg" class="information--left--profile__photo" alt="Avatar" />
                                </div>
                            </div>
                            <div class="manager__container-list-employee-item-fullname-value">
                                <span>Nguyễn Quang Pháp</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-code">
                            <div class="manager__container-list-employee-item-code-value">
                                <span>NV001</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-department">
                            <div class="manager__container-list-employee-item-department-value">
                                <span>Phòng IT</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-position">
                            <div class="manager__container-list-employee-item-position-value">
                                <span>Nhân viên</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="manager__container-list-employee-item">
                    <a class="manager__container-list-employee-item-link">
                        <div class="manager__container-list-employee-item-fullname">
                            <div class="manager__container-list-employee-item-fullname-image">
                                <div class="circular--landscape-list-employee">
                                    <img src="assets/img/profile.jpg" class="information--left--profile__photo" alt="Avatar" />
                                </div>
                            </div>
                            <div class="manager__container-list-employee-item-fullname-value">
                                <span>Nguyễn Quang Pháp</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-code">
                            <div class="manager__container-list-employee-item-code-value">
                                <span>NV001</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-department">
                            <div class="manager__container-list-employee-item-department-value">
                                <span>Phòng IT</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-position">
                            <div class="manager__container-list-employee-item-position-value">
                                <span>Nhân viên</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="manager__container-list-employee-item">
                    <a class="manager__container-list-employee-item-link">
                        <div class="manager__container-list-employee-item-fullname">
                            <div class="manager__container-list-employee-item-fullname-image">
                                <div class="circular--landscape-list-employee">
                                    <img src="assets/img/profile.jpg" class="information--left--profile__photo" alt="Avatar" />
                                </div>
                            </div>
                            <div class="manager__container-list-employee-item-fullname-value">
                                <span>Nguyễn Quang Pháp</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-code">
                            <div class="manager__container-list-employee-item-code-value">
                                <span>NV001</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-department">
                            <div class="manager__container-list-employee-item-department-value">
                                <span>Phòng IT</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-position">
                            <div class="manager__container-list-employee-item-position-value">
                                <span>Nhân viên</span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="manager__container-list-employee-item">
                    <a class="manager__container-list-employee-item-link">
                        <div class="manager__container-list-employee-item-fullname">
                            <div class="manager__container-list-employee-item-fullname-image">
                                <div class="circular--landscape-list-employee">
                                    <img src="assets/img/profile.jpg" class="information--left--profile__photo" alt="Avatar" />
                                </div>
                            </div>
                            <div class="manager__container-list-employee-item-fullname-value">
                                <span>Nguyễn Quang Pháp</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-code">
                            <div class="manager__container-list-employee-item-code-value">
                                <span>NV001</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-department">
                            <div class="manager__container-list-employee-item-department-value">
                                <span>Phòng IT</span>
                            </div>
                        </div>
                        <div class="manager__container-list-employee-item-position">
                            <div class="manager__container-list-employee-item-position-value">
                                <span>Nhân viên</span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>