<div class="row requestDR">
    <p class="requestDR__functionName">Yêu cầu thiết bị</p>

    <div class="col-6 requestDR__form">
        <div class="requestDR__formName">Tạo đề xuất</div>
        <form action="index.php?action=addRequestDR" method="POST">
            <div class="row requestDR__formItem">
                <span class="requestDR__formItemName">Tên *</sp>
                <input class="requestDR__formInput" type="text" name="requestName" required>
            </div>
            <div class="row requestDR__formItem">
                <span class="requestDR__formItemName">Loại *</sp>
                <select class="requestDR__request-session-input" name="type" aria-label="Default select example" require>
                    <option value="Phần cứng">Phần cứng</option>
                    <option value="Phần mềm">Phần mềm</option>
                </select>
            </div>
            <div class="row requestDR__formItem">
                <span class="requestDR__formItemName">Ghi chú </sp>
                <input class="requestDR__formInput" type="text" placeholder="Thông tin chi tiết thiết bị" name="noteRequest">
            </div>

            <div class="row requestDR__formItem">
                <span class="requestDR__formItemName">Lý do yêu cầu *</span>
                <input class="requestDR__formInput" type="text" name="reason" required>
            </div>
            <button type="submit" class="requestDR_submit-btn btn btn-success">Gửi đề xuất</button>
        </form>
    </div>

    <div class="col-6 requestDR__form--status">
        <p class="requestDR__formName--status">Trạng thái đơn đề xuất</p>
        <?php
            foreach ($dataAllRequest as $item)  {
                print"
                    <div class='row requestDR__formItems--status'>
                        <div class='col-8'>
                            <span class='requestDR__formItemsName'>
                                Tên thiết bị/ phần mềm: {$item->requestName}
                            </span>    
                            <span class='requestDR__formItemsNote'>
                                Ghi chú: {$item->noteRequest}
                            </span>   
                            <span class='requestDR__formItemsReason'>
                                Lý do: {$item->reason}
                            </span>     
                        </div>
                        <div class='col-4 requestDR__formItemsStatus'>
                            <span class='requestDR__formItemsStatusName'>
                                {$item->requestStatus}
                            </span>
                        </div>
                    </div>
                    <div class='requestDR__formItems--margin'></div>
                ";
            }
        ?>
    </div>
</div>

<?php require("js/employee_DR.phtml"); ?>