<div class="row requestDR">
    <p class="requestDR__functionName">Yêu cầu thiết bị</p>

    <div class="col-6 requestDR__form">
        <div class="requestDR__formName">Tạo đề xuất</div>
        <div class="row requestDR__formItem">
            <span class="requestDR__formItemName">Tên *</sp>
                <input class="requestDR__formInput" type="text">
        </div>
        <div class="row requestDR__formItem">
            <span class="requestDR__formItemName">Loại *</sp>
                <input class="requestDR__formInput" type="text" placeholder="Phần cứng/Phần mềm">
        </div>
        <div class="row requestDR__formItem">
            <span class="requestDR__formItemName">Ghi chú *</sp>
                <input class="requestDR__formInput" type="text" placeholder="Thông tin chi tiết thiết bị">
        </div>

        <div class="row requestDR__formItem">
            <span class="requestDR__formItemName">Lý do yêu cầu *</span>
            <input class="requestDR__formInput" type="text">
        </div>
        <button type="submit" class="requestDR_submit-btn btn btn-success">Gửi đề xuất</button>
        <button type="submit" class="requestDR_cancel-btn btn btn-danger">Hủy</button>
    </div>

    <div class="col-6 requestDR__form--status">
        <p class="requestDR__formName--status">Trạng thái đơn đề xuất</p>
        <div class="row requestDR__formItems--status">
            <div class="col-8">
                <span class="requestDR__formItemsName">
                    Tên thiết bị/ phần mềm: Máy tính xách tay Casio
                </span>
                <span class="requestDR__formItemsNote">
                    Ghi chú: Casio fx-1975 PLUS
                </span>
                <span class="requestDR__formItemsReason">
                    Lý do: Lười tính tay
                </span>
            </div>
            <div class="col-4 requestDR__formItemsStatus">
                <span class="requestDR__formItemsStatusName">
                    Đang chờ duyệt
                </span>
            </div>
        </div>
        <div class="row requestDR__formItems--status">
            <div class="col-8">
                <span class="requestDR__formItemsName">
                    Tên thiết bị/ phần mềm: Tài khoản office 365
                </span>
                <span class="requestDR__formItemsNote">
                    Ghi chú: Gói professional
                </span>
                <span class="requestDR__formItemsReason">
                    Lý do: Cần excel 2022
                </span>
            </div>
            <div class="col-4 requestDR__formItemsStatus">
                <span class="requestDR__formItemsStatusName">
                    Đang chờ duyệt
                </span>
            </div>
        </div>
    </div>
</div>