<div class="row requestA">
    <p class="requestA__functionName">Hoạt động của công ty</p>
    <div class="requestA_formName">
        <p class="requestA__formName--status">Danh sách các hoạt động</p>
        <form class="requestA-info__search d-flex">
            <input class="requestA-info_search_form form-control me-2" type="search"
                placeholder="Tìm kiếm tên hoạt động.." aria-label="Search">
            <button type="submit" class="requestA-info_search__btn btn btn-dark"><i
                    class="requestA-info_search__icon fas fa-search"></i></button>
        </form>
    </div>
    <div class="row requestA__formItems--status">
        <div class="col-9">
            <span class="requestA__formItemsName">
                Tên hoạt động: Bootcamp
            </span>
            <span class="requestA__formItemsDescription">
                Mô tả: Bootcamp là mô hình đào tạo dưới dạng trại huấn luyện cường độ cao
                trong thời gian ngắn,...
            </span>
            <span class="requestA__formItemsDeadline">
                Hạn chót: 20/20/2023
            </span>
        </div>
        <div class="col-3">
            <button type="submit" class="requestA_submit-btn btn btn-success">Đăng ký</button>
            <button type="submit" class="requestA_submit-btn btn btn-success">Theo dõi</button>
        </div>
    </div>
    <div class="row requestA__formItems--status">
        <div class="col-9">
            <span class="requestA__formItemsName">
                Tên hoạt động: Bootcamp
            </span>
            <span class="requestA__formItemsDescription">
                Mô tả: Bootcamp là mô hình đào tạo dưới dạng trại huấn luyện cường độ cao
                trong thời gian ngắn,...
            </span>
            <span class="requestA__formItemsDeadline">
                Hạn chót: 20/20/2023
            </span>
        </div>
        <div class="col-3">
            <button type="submit" class="requestA_submit-btn btn btn-success">Đăng ký</button>
            <button type="submit" class="requestA_submit-btn btn btn-success">Theo dõi</button>
        </div>
    </div>
    <div class="row requestA__formItems--status">
        <div class="col-9">
            <span class="requestA__formItemsName">
                Tên hoạt động: Bootcamp
            </span>
            <span class="requestA__formItemsDescription">
                Mô tả: Bootcamp là mô hình đào tạo dưới dạng trại huấn luyện cường độ cao
                trong thời gian ngắn,...
            </span>
            <span class="requestA__formItemsDeadline">
                Hạn chót: 20/20/2023
            </span>
        </div>
        <div class="col-3">
            <button type="submit" class="requestA_submit-btn btn btn-success">Đăng ký</button>
            <button type="submit" class="requestA_submit-btn btn btn-success">Theo dõi</button>
        </div>
    </div>
    <div class="row requestA__formItems--status">
        <div class="col-9">
            <span class="requestA__formItemsName">
                Tên hoạt động: Bootcamp
            </span>
            <span class="requestA__formItemsDescription">
                Mô tả: Bootcamp là mô hình đào tạo dưới dạng trại huấn luyện cường độ cao
                trong thời gian ngắn,...
            </span>
            <span class="requestA__formItemsDeadline">
                Hạn chót: 20/20/2023
            </span>
        </div>
        <div class="col-3">
            <button type="submit" class="requestA_submit-btn btn btn-success">Đăng ký</button>
            <button type="submit" class="requestA_submit-btn btn btn-success">Theo dõi</button>
        </div>
    </div>
    <div class="row requestA__formItems--status">
        <div class="col-9">
            <span class="requestA__formItemsName">
                Tên hoạt động: Bootcamp
            </span>
            <span class="requestA__formItemsDescription">
                Mô tả: Bootcamp là mô hình đào tạo dưới dạng trại huấn luyện cường độ cao
                trong thời gian ngắn,...
            </span>
            <span class="requestA__formItemsDeadline">
                Hạn chót: 20/20/2023
            </span>
        </div>
        <div class="col-3">
            <button type="submit" class="requestA_submit-btn btn btn-success">Đăng ký</button>
            <button type="submit" class="requestA_submit-btn btn btn-success">Theo dõi</button>
        </div>
    </div>
</div>