<div class="information__header">
    <div class="row">
        <div class="information__header_nav">
            <a class="information__header-nav-item">
                <i class="information__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="information__header-nav-item-name">Thông tin cá nhân</p>
            </a>
            <a class="information__header-nav-item">
                <i class="information__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="information__header-nav-item-name">Thông tin chính</p>
            </a>
        </div>
    </div>
</div>
<div class="information__container">
    <div class="row">
        <div class="col-3 information__container-left">
            <div class="row">
                <div class="information--left__element">
                    <div class="information--left--profile">
                        <div class="circular--landscape">
                            <img src="assets/img/profile.jpg" class="information--left--profile__photo" alt="Avatar" />
                        </div>
                        <span class="information--left--profile__fullname">Nguyễn Quang Pháp</span>
                        <span class="information--left--profile__position">Nhân viên</span>
                    </div>
                </div>
                <div class="information--left__element">
                    <div class="information--left--quickinfor">
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-qrcode"></i>
                            <span class="information--left--quickinfor__element-value">NV001</span>
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-briefcase"></i>
                            <span class="information--left--quickinfor__element-value">Nhân viên</span>
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-envelope"></i>
                            <span class="information--left--quickinfor__element-value">phaphtt@gmail.com</span>
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-square-phone"></i>
                            <span class="information--left--quickinfor__element-value">123456</span>
                        </div>
                    </div>
                </div>
                <div class="information--left__element">
                    <div class="information--left-functions">
                        <a url="" class="information--left-functions-item">
                            <div class="col-2 information--left-functions-left">
                                <i class="information--left-functions-left__icon fa-solid fa-user-large" style="color:var(--secondary-color);"></i>
                            </div>
                            <div class="col-10 information--left-functions-right">
                                    <span class="information--left-functions-right__title" style="color:var(--secondary-color);">Thông tin chính</span>
                                    <span class="information--left-functions-right__description" style="color:var(--secondary-color);">Thông tin lý lịch và pháp lý</span>
                            </div>
                        </a>
                        <a url="" class="information--left-functions-item">
                            <div class="col-2 information--left-functions-left">
                                <i class="information--left-functions-left__icon fa-solid fa-font-awesome"></i>
                            </div>
                            <div class="col-10 information--left-functions-right">
                                    <span class="information--left-functions-right__title">Thông tin công việc</span>
                                    <span class="information--left-functions-right__description">Thông tin công việc, sự nghiệp</span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-9 information__container-right">
            <div class="row" style="padding-bottom: 10px;">
                <div class="information__container-right__title">
                    <div class="row information__container-right__title-element">
                        <div class="col-8 information__container-right__title-left">
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__name">Thông tin chính</span>
                            </div>
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__description">Các thông tin cá nhân quan trọng</span>
                            </div>
                        </div>
                        <div class="col-4 information__container-right__title-right">
                            <div id="btn-update" class="update--infor">
                                
                            </div>
                        </div>
                    </div>
                </div>
                <div class="information__container-right__content">
                    <div class="row" style="padding-bottom: 10px;">
                        <div class="information__container-right__content-list">
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Mã nhân viên</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-value">NV0001<span>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Họ</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <input type="text" id="employee_firstname" class="information__container-right__content-list-field__element-value" onchange="checkInvalidValue(id);" value="Nguyễn Quang"></input>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Tên</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <input type="text" id="employee_lastname" class="information__container-right__content-list-field__element-value" onchange="checkInvalidValue(id);" value="Pháp"></input>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Tình trạng việc làm</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-value">Active</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="padding-bottom: 10px;">
                        <div class="information__container-right__content-list">
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Phòng ban</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <select id="employee_department" class="information__container-right__content-list-field__element-value">
                                        <option value="1" selected>Phòng IT</option>
                                        <option value="2">Kế toán</option>
                                    </select>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Chức vụ</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <select id="employee_position" class="information__container-right__content-list-field__element-value">
                                        <option value="nhanvien" selected>Nhân viên</option>
                                        <option value="truongphong">Trưởng Phòng</option>
                                    </select>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Ngày sinh</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <input type="date" id="employee_dayOfBirth" class="information__container-right__content-list-field__element-value" value=""></input>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Giới tính</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <select class="information__container-right__content-list-field__element-value">
                                        <option value="nam" selected>Nam</option>
                                        <option value="nu">Nữ</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="padding-bottom: 10px;border-bottom: 5px solid var(--angle-color);">
                        <div class="information__container-right__content-list">
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Email</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <input type="text" id="employee_email" class="information__container-right__content-list-field__element-value" value="phaphtt@gmail" onchange="checkInvalidValue(id);"></input>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Số điện thoại</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <input type="text" id="employee_phone" class="information__container-right__content-list-field__element-value" value="0368047874" onchange="checkInvalidValue(id);"></input>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Địa chỉ</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <input type="text" id="employee_address" class="information__container-right__content-list-field__element-value" value="Aasda" onchange="checkInvalidValue(id);"></input>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Tình trạng hôn nhân</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <select class="information__container-right__content-list-field__element-value">
                                        <option value="docthan" selected>Độc thân</option>
                                        <option value="dakethon">Đã kết hôn</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="information__container-right__title">
                    <div class="row information__container-right__title-element">
                        <div class="col-8 information__container-right__title-left">
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__name">Thông tin quản lý</span>
                            </div>
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__description">Thông tin cơ bản người quản lý</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="information__container-right__content">
                    <div class="row" style="padding-bottom: 10px;">
                        <div class="information__container-right__content-list">
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Mã nhân viên</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-value">NV0002</span>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Họ</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-value">Nguyễn Quang</span>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Tên</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-value">Pháp</span>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Giới tính</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-value">Nam</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="padding-bottom: 10px;">
                        <div class="information__container-right__content-list">
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Phòng ban</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-value">Phòng IT</span>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Chức vụ</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-value">Trưởng phòng</span>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Email</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-value">phaphtt@gmail</span>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Số điện thoại</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-value">0368047874</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require("js/employee_information.phtml"); ?>