<div class="information__header">
    <div class="row">
        <div class="information__header_nav">
            <a class="information__header-nav-item">
                <i class="information__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="information__header-nav-item-name">Thông tin cá nhân</p>
            </a>
            <a class="information__header-nav-item">
                <i class="information__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="information__header-nav-item-name">Thông tin công việc</p>
            </a>
        </div>
    </div>
</div>
<div class="information__container">
    <div class="row">
        <div class="col-3 information__container-left">
            <div class="row">
                <div class="information--left__element">
                    <div class="information--left--profile">
                        <div class="circular--landscape">
                            <img src="assets/img/profile.jpg" class="information--left--profile__photo" alt="Avatar" />
                        </div>
                        <span class="information--left--profile__fullname">Nguyễn Quang Pháp</span>
                        <span class="information--left--profile__position">Nhân viên</span>
                    </div>
                </div>
                <div class="information--left__element">
                    <div class="information--left--quickinfor">
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-qrcode"></i>
                            <span class="information--left--quickinfor__element-value">NV001</span>
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-briefcase"></i>
                            <span class="information--left--quickinfor__element-value">Nhân viên</span>
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-envelope"></i>
                            <span class="information--left--quickinfor__element-value">phaphtt@gmail.com</span>
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-square-phone"></i>
                            <span class="information--left--quickinfor__element-value">123456</span>
                        </div>
                    </div>
                </div>
                <div class="information--left__element">
                    <div class="information--left-functions">
                        <a class="information--left-functions-item">
                            <div class="col-2 information--left-functions-left">
                                <i class="information--left-functions-left__icon fa-solid fa-user-large"></i>
                            </div>
                            <div class="col-10 information--left-functions-right">
                                    <span class="information--left-functions-right__title">Thông tin chính</span>
                                    <span class="information--left-functions-right__description">Thông tin lý lịch và pháp lý</span>
                            </div>
                        </a>
                        <a url="" class="information--left-functions-item">
                            <div class="col-2 information--left-functions-left">
                                <i class="information--left-functions-left__icon fa-solid fa-font-awesome"  style="color:var(--secondary-color);"></i>
                            </div>
                            <div class="col-10 information--left-functions-right">
                                    <span class="information--left-functions-right__title" style="color:var(--secondary-color);">Thông tin công việc</span>
                                    <span class="information--left-functions-right__description" style="color:var(--secondary-color);">Thông tin công việc, sự nghiệp</span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-9 information__container-right">
            <div class="row" style="padding-bottom: 10px;">
                <div class="information__container-right__title">
                    <div class="row information__container-right__title-element">
                        <div class="col-8 information__container-right__title-left">
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__name">Danh sách công việc</span>
                            </div>
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__description">Danh sách các công việc và trạng thái</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="information__container-right__filter">
                    <div class="row" style="border-bottom: 1px solid var(--angle-color);">
                        <div class="information__container-right__filter-list">
                            <div class="information__container-right__filter-list-item">
                                <select class="information__container-right__filter-list-item__element">
                                    <option value="all">Tất cả trạng thái</option>
                                </select>
                            </div>
                            <div class="information__container-right__filter-list-item">
                                <select class="information__container-right__filter-list-item__element">
                                    <option value="all">Tất cả dự án</option>
                                </select>
                            </div>
                            <div class="information__container-right__filter-list-item">
                                <select class="information__container-right__filter-list-item__element">
                                    <option value="all">Giao & Được giao</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="information__container-right__content">
                    <div class="row">
                        <div class="information__container-right__content-list">
                            <div class="information__container-right__content-list-title">
                                <div class="information__container-right__content-list-title__work">
                                    <span>CÔNG VIỆC</span>
                                </div>
                                <div class="information__container-right__content-list-title__department">
                                    <span>PHÒNG BAN</span>
                                </div>
                                <div class="information__container-right__content-list-title__project">
                                    <span>DỰ ÁN</span>
                                </div>
                                <div class="information__container-right__content-list-title__status">
                                    <span>TRẠNG THÁI</span>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-item">
                                <a class="information__container-right__content-list-item-link">
                                    <div class="information__container-right__content-list-item-link-job">
                                        <span class="information__container-right__content-list-item-link-job-value">Công việc A</span>
                                    </div>
                                    <div class="information__container-right__content-list-item-link-department">
                                        <span class="information__container-right__content-list-item-link-department-value">Phòng IT</span>
                                    </div>
                                    <div class="information__container-right__content-list-item-link-project">
                                        <span class="information__container-right__content-list-item-link-project-value">Dự án A</span>
                                    </div>
                                    <div class="information__container-right__content-list-item-link-status">
                                        <span class="information__container-right__content-list-item-link-status-value">Hoàn thành</span>
                                    </div>
                                </a>
                            </div>
                            <div class="information__container-right__content-list-item">
                                <a class="information__container-right__content-list-item-link">
                                    <div class="information__container-right__content-list-item-link-job">
                                        <span class="information__container-right__content-list-item-link-job-value">Công việc A</span>
                                    </div>
                                    <div class="information__container-right__content-list-item-link-department">
                                        <span class="information__container-right__content-list-item-link-department-value">Phòng IT</span>
                                    </div>
                                    <div class="information__container-right__content-list-item-link-project">
                                        <span class="information__container-right__content-list-item-link-project-value">Dự án A</span>
                                    </div>
                                    <div class="information__container-right__content-list-item-link-status">
                                        <span class="information__container-right__content-list-item-link-status-value">Đang thực hiện</span>
                                    </div>
                                </a>
                            </div>
                            <div class="information__container-right__content-list-item">
                                <a class="information__container-right__content-list-item-link">
                                    <div class="information__container-right__content-list-item-link-job">
                                        <span class="information__container-right__content-list-item-link-job-value">Công việc A</span>
                                    </div>
                                    <div class="information__container-right__content-list-item-link-department">
                                        <span class="information__container-right__content-list-item-link-department-value">Phòng IT</span>
                                    </div>
                                    <div class="information__container-right__content-list-item-link-project">
                                        <span class="information__container-right__content-list-item-link-project-value">Dự án A</span>
                                    </div>
                                    <div class="information__container-right__content-list-item-link-status">
                                        <span class="information__container-right__content-list-item-link-status-value">Quá hạn</span>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php require("js/employee_tasks.phtml"); ?>
