<div class="row requestWFH">
    <p class="requestWFH__functionName">Xin làm việc tại nhà</p>
    <div class="col-6 requestWFH__form">
        <div class="requestWFH__formName">Tạo đề xuất</div>
        <form action="index.php?action=addRequestWFH" method="POST">
            <div class="row requestWFH__formItem">
                <span class="requestWFH__formItemName">Ngày bắt đầu *</sp>
                <input class="requestWFH__formInput" type="date" id="idstartDayWFH" name="startDayWFH" required value="<?php if(isset($_POST['startDayWFH'])){echo $_POST['startDayWFH']; } ?>" onblur="CheckDateStart(id);">
            </div>
            <div class="row requestWFH__formItem">
                <span class="requestWFH__formItemName">Ngày kết thúc *</sp>
                <input class="requestWFH__formInput" type="date" id="idendDayWFH" name="endDayWFH" required value="<?php if(isset($_POST['endDayWFH'])){echo $_POST['endDayWFH']; } ?>" onblur="CheckDateEnd(id);">
            </div>
            <div class="row requestWFH__formItem">
                <span class="requestWFH__formItemName">Lý do làm tại nhà *</span>
                <input class="requestWFH__formInput" type="text" name="reason" required value="<?php if(isset($_POST['reason'])){echo $_POST['reason']; } ?>">
            </div>
            <button type="submit" class="requestWFH_submit-btn btn btn-success">Gửi đề xuất</button>
        </form>
    </div>
    <div class="col-6 requestWFH__form--status">
        <p class="requestWFH__formName--status">Trạng thái đơn đề xuất</p>
        <?php
        if(isset($dataAllRequest)){
            foreach ($dataAllRequest as $item) 
            {
            ?>
                <div class="row requestWFH__formItems--status">
                    <div class="col-8">
                        <span class="requestWFH__formItemsDate">
                            Xin làm tại nhà
                        </span> 
                        <span class="requestWFH__formItemsDate">
                            Ngày bắt đầu: <?php echo date('d-m-Y',strtotime($item['startDayWFH']));?>
                        </span>
                        <span class="requestWFH__formItemsDate">
                            Ngày kết thúc: <?php echo date('d-m-Y',strtotime($item['endDayWFH']));?>
                        </span>   
                        <span class="requestWFH__formItemsReason">
                            Lý do: <?php echo "{$item['reason']}";?>
                        </span>  
                        <span class="requestWFH__formItemsRejectReason">
                            Lý do từ chối: <?php echo "{$item['requestRejectReason']}";?>
                        </span>  
                    </div>
                    <div class="col-4 requestWFH__formItemsStatus">
                        <span class="requestWFH__formItemsStatusName">
                            <?php echo "{$item['requestStatus']}";?>
                        </span>
                    </div>
                </div>
            <?php
            }
        }
        ?>
        <div class="requestWFH__formItems--margin"></div>
    </div>
</div>

<?php require("js/employee_WFH.phtml"); ?>