<div class="information__header">
    <div class="row">
        <div class="information__header_nav">
            <a class="information__header-nav-item">
                <i class="information__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="information__header-nav-item-name">Thông tin cá nhân</p>
            </a>
            <a class="information__header-nav-item">
                <i class="information__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="information__header-nav-item-name">Thông tin công việc</p>
            </a>
        </div>
    </div>
</div>
<div class="information__container">
    <div class="row">
        <div class="col-3 information__container-left">
            <div class="row">
                <div class="information--left__element">
                    <div class="information--left--profile">
                        <div class="circular--landscape">
                            <img src="assets/img/profile.jpg" class="information--left--profile__photo" alt="Avatar" />
                        </div>
                        <span class="information--left--profile__fullname">Nguyễn Quang Pháp</span>
                        <span class="information--left--profile__position">Nhân viên</span>
                    </div>
                </div>
                <div class="information--left__element">
                    <div class="information--left--quickinfor">
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-qrcode"></i>
                            <span class="information--left--quickinfor__element-value">NV001</span>
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-briefcase"></i>
                            <span class="information--left--quickinfor__element-value">Nhân viên</span>
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-envelope"></i>
                            <span class="information--left--quickinfor__element-value">phaphtt@gmail.com</span>
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-square-phone"></i>
                            <span class="information--left--quickinfor__element-value">123456</span>
                        </div>
                    </div>
                </div>
                <div class="information--left__element">
                    <div class="information--left-functions">
                        <a class="information--left-functions-item">
                            <div class="col-2 information--left-functions-left">
                                <i class="information--left-functions-left__icon fa-solid fa-user-large"></i>
                            </div>
                            <div class="col-10 information--left-functions-right">
                                    <span class="information--left-functions-right__title">Thông tin chính</span>
                                    <span class="information--left-functions-right__description">Thông tin lý lịch và pháp lý</span>
                            </div>
                        </a>
                        <a url="" class="information--left-functions-item">
                            <div class="col-2 information--left-functions-left">
                                <i class="information--left-functions-left__icon fa-solid fa-font-awesome"  style="color:var(--secondary-color);"></i>
                            </div>
                            <div class="col-10 information--left-functions-right">
                                    <span class="information--left-functions-right__title" style="color:var(--secondary-color);">Thông tin công việc</span>
                                    <span class="information--left-functions-right__description" style="color:var(--secondary-color);">Thông tin công việc, sự nghiệp</span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-9 information__container-right">
            <div class="row" style="padding-bottom: 10px;">
                <div class="information__container-right__title">
                    <div class="row information__container-right__title-element">
                        <div class="col-8 information__container-right__title-left">
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__name">Danh sách công việc</span>
                            </div>
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__description">Danh sách các công việc và trạng thái</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="information__container-right__filter">
                    <div class="row" style="border-bottom: 1px solid var(--angle-color);">
                        <div class="information__container-right__filter-list">
                            <div class="information__container-right__filter-list-item">
                                <select class="information__container-right__filter-list-item__element">
                                    <option value="all">Tất cả trạng thái</option>
                                </select>
                            </div>
                            <div class="information__container-right__filter-list-item">
                                <select class="information__container-right__filter-list-item__element">
                                    <option value="all">Tất cả dự án</option>
                                </select>
                            </div>
                            <div class="information__container-right__filter-list-item">
                                <select class="information__container-right__filter-list-item__element">
                                    <option value="all">Giao & Được giao</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="information__container-right__content">
                    <div class="row">
                        <table>
                            <thead>
                                <tr class="information__container-right__content-table--title">
                                    <th class="col-6">
                                        <span class="information__container-right__content-table--title-value">CÔNG VIỆC</span>
                                    </th>
                                    <th class="col-2">
                                        <span class="information__container-right__content-table--title-value">PHÒNG BAN</span>
                                    </th>
                                    <th class="col-2">
                                        <span class="information__container-right__content-table--title-value">DỰ ÁN</span>
                                    </th>
                                    <th class="col-2">
                                        <span class="information__container-right__content-table--title-value">TRẠNG THÁI</span>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="information__container-right__content-table--row" data-href="">
                                    <td>
                                        <span>Công việc </span>
                                    </td>
                                    <td>
                                        <span>Phòng IT</span>
                                    </td>
                                    <td>
                                        <span>Dự án Á</span>
                                    </td>
                                    <td>
                                        <span style="background-color:var(--green-color); background-clip: content-box; color:var(--white-color);">Hoàn thành</span>
                                    </td>
                                </tr>
                                <tr class="information__container-right__content-table--row" data-href="">
                                    <td>
                                        <span>Công việc </span>
                                    </td>
                                    <td>
                                        <span>Phòng IT</span>
                                    </td>
                                    <td>
                                        <span>Dự án Á</span>
                                    </td>
                                    <td>
                                        <span style="background-color:var(--orange-color); background-clip: content-box; color:var(--white-color);">Đang thực hiện</span>
                                    </td>
                                </tr>
                                <tr class="information__container-right__content-table--row" data-href="">
                                    <td>
                                        <span>Công việc </span>
                                    </td>
                                    <td>
                                        <span>Phòng IT</span>
                                    </td>
                                    <td>
                                        <span>Dự án Á</span>
                                    </td>
                                    <td>
                                        <span style="background-color:var(--red-color); background-clip: content-box; color:var(--white-color);">Quá hạn</span>
                                    </td>
                                </tr>
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>