<div class="row requestOFF">
    <p class="requestOFF__functionName">Xin nghỉ phép</p>

    <div class="col-6 requestOFF__form">
        <div class="requestOFF__formName">Tạo đề xuất</div>
        <form action="index.php?action=addRequestOFF" method="POST">
            <div class="row requestOFF__formItem">
                <span class="requestOFF__formItemName">Ngày xin nghỉ *</sp>
                <input class="requestOFF__formInput requestOFF__formInput-date" name="startDayOFF" onblur="TDate()" required type="date">
            </div>
            <div class="row requestOFF__formItem">
                <span class="requestOFF__formItemName">Số ngày nghỉ *</sp>
                <input class="requestOFF__formInput requestOFF__formInput-dayoff" name="numberDayOFF" required onchange="DayOffExpected()" type="number">
            </div>
            <div class="row requestOFF__formItem">
                <span class="requestOFF__formItemName">Ghi chú nghỉ </sp>
                <input class="requestOFF__formInput requestOFF__formInput-noteoff" name="noteDayOFF" type="text" placeholder="Sáng/chiều/cả ngày">
            </div>
            
            <div class="row requestOFF__formItem">
                <span class="requestOFF__formItemName">Lý do nghỉ phép *</span>
                <input class="requestOFF__formInput requestOFF__formInput-reasonoff" name="reason" type="text" required>
            </div>
            <button type="submit" class="requestOFF_submit-btn btn btn-success">Gửi đề xuất</button>
        </form>    
    </div>

    <div class="col-6 requestOFF__form--status">
        <p class="requestOFF__formName--status">Trạng thái đơn đề xuất</p>
        <?php
            $pagesize = 10;
            $currentpage = 1;
            $numrow = count($dataAllRequest);
            $self = $_SERVER['PHP_SELF'];
            $nav = "";
            $numpage = ceil($numrow / ($pagesize*1.0));
            
            if (isset($_REQUEST["page"]))
                $currentpage = $_REQUEST["page"];
            
            $start = ($currentpage - 1) * $pagesize;
            $end = $start + $pagesize - 1;
            
            if ($end > $numrow - 1)
                $end = $numrow - 1;

            while($start<=$end) {
                print"
                    <div class='row requestOFF__formItems--status'>
                        <div class='col-8'>
                            <span class='requestOFF__formItemsDate'>
                                Xin nghỉ ngày {$dataAllRequest[$start]->startDayOFF}
                            </span>    
                            <span class='requestOFF__formItemsHour'>
                                Số ngày nghỉ: {$dataAllRequest[$start]->numberDayOFF}
                            </span>   
                            <span class='requestOFF__formItemsHour'>
                                Ghi chú nghỉ: {$dataAllRequest[$start]->noteDayOFF}
                            </span>     
                            <span class='requestOFF__formItemsReason'>
                                Lý do: {$dataAllRequest[$start]->reason}
                            </span>  
                            <span class='requestOFF__formItemsRejectReason'>
                                Lý do từ chối: {$dataAllRequest[$start]->requestRejectReason}
                            </span>  
                        </div>
                        <div class='col-4 requestOFF__formItemsStatus'>
                            <span class='requestOFF__formItemsStatusName'>
                                {$dataAllRequest[$start]->requestStatus}
                            </span>
                        </div>
                    </div>
                    <div class='requestOFF__formItems--margin'></div>
                ";
            $start+=1;
            }
        ?>

        <!-- <div class="row requestOFF__formItems--status">
            <div class="col-8">
                <span class="requestOFF__formItemsDate">
                    Xin nghỉ ngày 12/07/2022
                </span>    
                <span class="requestOFF__formItemsHour">
                    Số ngày nghỉ: 3
                </span>   
                <span class="requestOFF__formItemsHour">
                    Ghi chú nghỉ: cả ngày
                </span>     
                <span class="requestOFF__formItemsReason">
                    Lý do: cưới vợ
                </span>  
                <span class="requestOFF__formItemsRejectReason">
                    Lý do từ chối: dự án sắp đến hạn nộp
                </span>  
            </div>
            <div class="col-4 requestOFF__formItemsStatus">
                <span class="requestOFF__formItemsStatusName">
                    Chấp thuận
                </span>
            </div>
        </div>
        <div class="requestOFF__formItems--margin"></div>
        <div class="row requestOFF__formItems--status">
            <div class="col-8">
                <span class="requestOFF__formItemsDate">
                    Xin nghỉ ngày 12/07/2022
                </span>    
                <span class="requestOFF__formItemsHour">
                    Số ngày nghỉ: 3
                </span>   
                <span class="requestOFF__formItemsHour">
                    Ghi chú nghỉ: cả ngày
                </span>     
                <span class="requestOFF__formItemsReason">
                    Lý do: cưới vợ
                </span>  
                <span class="requestOFF__formItemsRejectReason">
                    Lý do từ chối: dự án sắp đến hạn nộp
                </span>  
            </div>
            <div class="col-4 requestOFF__formItemsStatus">
                <span class="requestOFF__formItemsStatusName">
                    Từ chối
                </span>
            </div>
        </div>
        <div class="requestOFF__formItems--margin"></div> -->
        
    </div>
</div>

<?php require("js/employee_OFF.phtml"); ?>
