<div class="manager__header">
    <div class="row">
        <div class="manager__header_nav">
            <a class="manager__header-nav-item">
                <i class="manager__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="manager__header-nav-item-name">Quản lý nhân viên</p>
            </a>
        </div>
    </div>
</div>
<div class="manager__container">
    <div class="row">
        <div class="manager__container-title">
            <div class="manager__container-title-first">
                <div class="manager__container-title-first__name">
                    <spa>Danh sách nhân viên</spa>
                </div>
            </div>
        </div>
        <div class="manager__container-list">
            <div class="manager__container-list-title">
                <div class="manager__container-list-title-name">
                    <span>NHÂN VIÊN</span>
                </div>
                <div class="manager__container-list-title-code">
                    <span>MÃ NV</span>
                </div>
                <div class="manager__container-list-title-department">
                    <span>PHÒNG BAN</span>
                </div>
                <div class="manager__container-list-title-position">
                    <span>CHỨC VỤ</span>
                </div>
            </div>
            <div class="manager__container-list-employee">
                <?php
                    $self = $_SERVER['PHP_SELF'];
                    $currentPage = 1;
                    if (isset($_REQUEST["page"]))
                        $currentPage = $_REQUEST["page"];
                    $n = count($data);
                    $i = 0;
                    while($i < $n){
                        $fullname = $data[$i]['firstname']." ".$data[$i]['lastname'];
                        echo "<div class='manager__container-list-employee-item'>
                                <a href='index.php?action=information&idEmployee={$data[$i]['id']}' class='manager__container-list-employee-item-link'>
                                    <div class='manager__container-list-employee-item-fullname'>
                                        <div class='manager__container-list-employee-item-fullname-image'>
                                            <div class='circular--landscape-list-employee'>
                                                <img src='assets/img/profile.png' class='information--left--profile__photo' alt='Avatar' />
                                            </div>
                                        </div>
                                        <div class='manager__container-list-employee-item-fullname-value'>
                                            <span>$fullname</span>
                                        </div>
                                    </div>
                                    <div class='manager__container-list-employee-item-code'>
                                        <div class='manager__container-list-employee-item-code-value'>
                                            <span>{$data[$i]['idEmployee']}</span>
                                        </div>
                                    </div>
                                    <div class='manager__container-list-employee-item-department'>
                                        <div class='manager__container-list-employee-item-department-value'>
                                            <span>{$data[$i]['departmentName']}</span>
                                        </div>
                                    </div>
                                    <div class='manager__container-list-employee-item-position'>
                                        <div class='manager__container-list-employee-item-position-value'>
                                            <span>{$data[$i]['position']}</span>
                                        </div>
                                    </div>
                                </a>
                            </div>";
                        $i += 1;
                    }
                ?>
            </div>
            <div class="information__container-right__content-list-paging">
                <div class="information__container-right__content-list-paging-element">
                    <?php
                        if ($currentPage > 1)
                        {
                            $page = $currentPage - 1;
                            $prev = "<a class='paging-data' href='$self?action=managerEmployee&idManager=$idManager&page=$page'><</a>     ";
                        }
                        else
                        {
                            $prev = "<a class='paging-data' href='$self?action=managerEmployee&idManager=$idManager&page=1'><</a>     ";
                        }


                        $page = $currentPage + 1;
                        $next = "     <a class='paging-data' href='$self?action=managerEmployee&idManager=$idManager&page=$page'>></a>";

                        echo $prev.$currentPage.$next;
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>