<div class="row requestOFF">
    <p class="requestOFF__functionName">Xin nghỉ phép</p>

    <div class="col-6 requestOFF__form">
        <div class="requestOFF__formName">Tạo đề xuất</div>
        <div class="row requestOFF__formItem">
            <span class="requestOFF__formItemName">Ngày xin nghỉ *</sp>
            <input class="requestOFF__formInput requestOFF__formInput-date" onblur="TDate()" type="date">
        </div>
        <div class="row requestOFF__formItem">
            <span class="requestOFF__formItemName">Số ngày nghỉ *</sp>
            <input class="requestOFF__formInput requestOFF__formInput-dayoff" onblur="DayOffExpected()" type="number">
        </div>
        <div class="row requestOFF__formItem">
            <span class="requestOFF__formItemName">Ghi chú nghỉ </sp>
            <input class="requestOFF__formInput requestOFF__formInput-noteoff" type="text" placeholder="Sáng/chiều/cả ngày">
        </div>
        
        <div class="row requestOFF__formItem">
            <span class="requestOFF__formItemName">Lý do nghỉ phép *</span>
            <input class="requestOFF__formInput requestOFF__formInput-reasonoff" type="text">
        </div>
        <button type="submit" onclick="submitRequestOFF()" class="requestOFF_submit-btn btn btn-success">Gửi đề xuất</button>
    </div>

    <div class="col-6 requestOFF__form--status">
        <p class="requestOFF__formName--status">Trạng thái đơn đề xuất</p>
        <div class="row requestOFF__formItems--status">
            <div class="col-8">
                <span class="requestOFF__formItemsDate">
                    Xin nghỉ ngày 12/07/2022
                </span>    
                <span class="requestOFF__formItemsHour">
                    Số ngày nghỉ: 3
                </span>   
                <span class="requestOFF__formItemsHour">
                    Ghi chú nghỉ: cả ngày
                </span>     
                <span class="requestOFF__formItemsReason">
                    Lý do: cưới vợ
                </span>  
                <span class="requestOFF__formItemsRejectReason">
                    Lý do từ chối: dự án sắp đến hạn nộp
                </span>  
            </div>
            <div class="col-4 requestOFF__formItemsStatus">
                <span class="requestOFF__formItemsStatusName">
                    Chưa xét duyệt
                </span>
            </div>
        </div>
        <div class="requestOFF__formItems--margin"></div>


        <!-- <div class="row requestOFF__formItems--status">
            <div class="col-8">
                <span class="requestOFF__formItemsDate">
                    Xin nghỉ ngày 12/07/2022
                </span>    
                <span class="requestOFF__formItemsHour">
                    Số ngày nghỉ: 3
                </span>   
                <span class="requestOFF__formItemsHour">
                    Ghi chú nghỉ: cả ngày
                </span>     
                <span class="requestOFF__formItemsReason">
                    Lý do: cưới vợ
                </span>  
                <span class="requestOFF__formItemsRejectReason">
                    Lý do từ chối: dự án sắp đến hạn nộp
                </span>  
            </div>
            <div class="col-4 requestOFF__formItemsStatus">
                <span class="requestOFF__formItemsStatusName">
                    Chấp thuận
                </span>
            </div>
        </div>
        <div class="requestOFF__formItems--margin"></div>
        <div class="row requestOFF__formItems--status">
            <div class="col-8">
                <span class="requestOFF__formItemsDate">
                    Xin nghỉ ngày 12/07/2022
                </span>    
                <span class="requestOFF__formItemsHour">
                    Số ngày nghỉ: 3
                </span>   
                <span class="requestOFF__formItemsHour">
                    Ghi chú nghỉ: cả ngày
                </span>     
                <span class="requestOFF__formItemsReason">
                    Lý do: cưới vợ
                </span>  
                <span class="requestOFF__formItemsRejectReason">
                    Lý do từ chối: dự án sắp đến hạn nộp
                </span>  
            </div>
            <div class="col-4 requestOFF__formItemsStatus">
                <span class="requestOFF__formItemsStatusName">
                    Từ chối
                </span>
            </div>
        </div>
        <div class="requestOFF__formItems--margin"></div> -->
        
    </div>
</div>

<?php require("js/employee_OFF.phtml"); ?>
