<div class="row requestOT">
    <p class="requestOT__functionName">Xin làm thêm giờ</p>

    <div class="col-6 requestOT__form">
        <div class="requestOT__formName">Tạo đề xuất</div>
        <div class="row requestOT__formItem">
            <span class="requestOT__formItemName">Ngày làm thêm giờ *</sp>
            <input class="requestOT__formInput requestOT__formInput-date" onblur="TDate()" type="date">
        </div>
        <div class="row requestOT__formItem">
            <span class="requestOT__formItemName">Số giờ dự kiến *</sp>
            <input class="requestOT__formInput requestOT__formInput-hour" onblur="HourExpected()" type="number">
        </div>
        <div class="row requestOT__formItem">
            <span class="requestOT__formItemName">Lý do làm thêm giờ *</span>
            <input class="requestOT__formInput requestOT__formInput-reasonOT" type="text">
        </div>
        <button type="submit" onclick="submitRequestOT()" class="requestOT_submit-btn btn btn-success">Gửi đề xuất</button>
    </div>

    <div class="col-6 requestOT__form--status">
        <p class="requestOT__formName--status">Trạng thái đơn đề xuất</p>
        <div class="row requestOT__formItems--status">
            <div class="col-8">
                <span class="requestOT__formItemsDate">
                    Xin làm thêm giờ ngày 12/07/2022
                </span>    
                <span class="requestOT__formItemsHour">
                    Số giờ: 4
                </span>    
                <span class="requestOT__formItemsReason">
                    Lý do: chậm tiến độ công việc
                </span>  
                <span class="requestOT__formItemsRejectReason">
                    Lý do từ chối: dự án sắp đến hạn nộp
                </span>  
            </div>
            <div class="col-4 requestOT__formItemsStatus">
                <span class="requestOT__formItemsStatusName">Đang chờ duyệt</span>
            </div>
        </div>
        <div class="requestOT__formItems--margin"></div>
        <div class="row requestOT__formItems--status">
            <div class="col-8">
                <span class="requestOT__formItemsDate">
                    Xin làm thêm giờ ngày 12/07/2022
                </span>    
                <span class="requestOT__formItemsHour">
                    Số giờ: 4
                </span>    
                <span class="requestOT__formItemsReason">
                    Lý do: chậm tiến độ công việc
                </span>  
                <span class="requestOT__formItemsRejectReason">
                    Lý do từ chối: dự án sắp đến hạn nộp
                </span>  
            </div>
            <div class="col-4 requestOT__formItemsStatus">
                <span class="requestOT__formItemsStatusName">
                    Chấp thuận
                </span>
            </div>
        </div>
        <div class="requestOT__formItems--margin"></div>
        <div class="row requestOT__formItems--status">
            <div class="col-8">
                <span class="requestOT__formItemsDate">
                    Xin làm thêm giờ ngày 12/07/2022
                </span>    
                <span class="requestOT__formItemsHour">
                    Số giờ: 4
                </span>    
                <span class="requestOT__formItemsReason">
                    Lý do: chậm tiến độ công việc
                </span>  
                <span class="requestOT__formItemsRejectReason">
                    Lý do từ chối: dự án sắp đến hạn nộp
                </span>  
            </div>
            <div class="col-4 requestOT__formItemsStatus">
                <span class="requestOT__formItemsStatusName">
                    Từ chối
                </span>
            </div>
        </div>
        <div class="requestOT__formItems--margin"></div>


    </div>
</div>

<?php require("js/employee_OT.phtml"); ?>
<?php require("js/jquery.phtml"); ?>