<div class="information__header">
    <div class="row">
        <div class="information__header_nav">
            <a class="information__header-nav-item">
                <i class="information__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="information__header-nav-item-name">Thông tin cá nhân</p>
            </a>
            <a class="information__header-nav-item">
                <i class="information__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="information__header-nav-item-name">Thông tin chính</p>
            </a>
        </div>
    </div>
</div>
<div class="information__container">
    <div class="row">
        <div class="col-3 information__container-left">
            <div class="row">
                <div class="information--left__element">
                    <div class="information--left--profile">
                        <div class="circular--landscape">
                            <img src="assets/img/profile.png" class="information--left--profile__photo" alt="Avatar" />
                        </div>
                        <?php 
                            $employeeName = $data["firstname"]." ".$data["lastname"];
                            echo "<span class='information--left--profile__fullname'>".$employeeName."</span>";
                        ?>
                        <?php
                            $roleName = $_SESSION['roleName'];
                            echo "<span class='information--left--profile__position'>".$roleName."</span>";
                        ?>
                    </div>
                </div>
                <div class="information--left__element">
                    <div class="information--left--quickinfor">
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-qrcode"></i>
                            <?php
                                echo "<span class='information--left--quickinfor__element-value'>".$data["idEmployee"]."</span>";
                            ?>
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-briefcase"></i>
                            <?php
                                echo "<span class='information--left--quickinfor__element-value'>".$data["position"]."</span>";
                            ?>
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-envelope"></i>
                            <?php
                                echo "<span class='information--left--quickinfor__element-value'>".$data["email"]."</span>";
                            ?>
                            
                        </div>
                        <div class="information--left--quickinfor__element">
                            <i class="information--left--quickinfor__element-icon fa-solid fa-square-phone"></i>
                            <?php
                                echo "<span class='information--left--quickinfor__element-value'>".$data["phoneNumber"]."</span>";
                            ?> 
                        </div>
                    </div>
                </div>
                <div class="information--left__element">
                    <div class="information--left-functions">
                        <?php
                            $idEmployee = $_REQUEST['idEmployee'];
                            echo "<a href='index.php?action=information&idEmployee={$idEmployee}' class='information--left-functions-item'>
                            <div class='col-2 information--left-functions-left'>
                                <i class='information--left-functions-left__icon fa-solid fa-user-large' style='color:var(--secondary-color);'></i>
                            </div>
                            <div class='col-10 information--left-functions-right'>
                                    <span class='information--left-functions-right__title' style='color:var(--secondary-color);'>Thông tin chính</span>
                                    <span class='information--left-functions-right__description' style='color:var(--secondary-color);'>Thông tin lý lịch và pháp lý</span>
                            </div>
                        </a>";
                        ?>
                        <?php
                            $idEmployee = $_REQUEST['idEmployee'];
                            echo "<a href='index.php?action=task&idEmployee={$idEmployee}&page=1&status=all' class='information--left-functions-item'>
                            <div class='col-2 information--left-functions-left'>
                                <i class='information--left-functions-left__icon fa-solid fa-font-awesome'></i>
                            </div>
                            <div class='col-10 information--left-functions-right'>
                                    <span class='information--left-functions-right__title'>Thông tin công việc</span>
                                    <span class='information--left-functions-right__description'>Thông tin công việc, sự nghiệp</span>
                            </div>
                        </a>";
                        ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-9 information__container-right">
            <div class="row" style="padding-bottom: 10px;">
                <form class="row" method="post">
                    <input type="hidden" name="action" value="information"></input>
                    <input type="hidden" name="func" value="update"></input>
                    <?php
                        echo "<input type='hidden' name='idEmployee' value={$data["id"]}></input>";
                    ?>
                    <div class="information__container-right__title">
                        <div class="row information__container-right__title-element">
                            <div class="col-8 information__container-right__title-left">
                                <div class="information__container-right__title-left-element">
                                    <span class="information__container-right__title-left-element__name">Thông tin chính</span>
                                </div>
                                <div class="information__container-right__title-left-element">
                                    <span class="information__container-right__title-left-element__description">Các thông tin cá nhân quan trọng</span>
                                </div>
                            </div>
                            <div class="col-4 information__container-right__title-right">
                                <div id="btn-update" class="update--infor">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="information__container-right__content">
                        <div class="row" style="padding-bottom: 10px;">
                            <div class="information__container-right__content-list">
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Mã nhân viên</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <?php
                                            echo "<span class='information__container-right__content-list-field__element-value'>".$data["idEmployee"]."<span>";
                                        ?>
                                        
                                    </div>
                                </div>
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Họ</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <?php
                                            echo "<input type='text' name='firstname' id='employee_firstname' class='information__container-right__content-list-field__element-value' onchange='checkInvalidValue(id);' value='{$data["firstname"]}'></input>";
                                        ?>
                                        
                                    </div>
                                </div>
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Tên</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <?php
                                            echo "<input type='text' name='lastname' id='employee_lastname' class='information__container-right__content-list-field__element-value' onchange='checkInvalidValue(id);' value='{$data["lastname"]}'></input>";
                                        ?>
                                    </div>
                                </div>
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Tình trạng việc làm</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <?php
                                            if($data["active"] == 1){
                                                echo "<span class='information__container-right__content-list-field__element-value' style='color:var(--green-color);'>Active</span>";
                                            }
                                            else
                                                echo "<span class='information__container-right__content-list-field__element-value' style='color:var(--red-color);'>Out</span>";
                                        ?>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="padding-bottom: 10px;">
                            <div class="information__container-right__content-list">
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Phòng ban</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <select name='idDepartment' id="employee_department" class="information__container-right__content-list-field__element-value" onchange="checkInvalidValue(id);">
                                            <?php
                                                $n = count($department);
                                                $i = 0;
                                                while($i < $n){
                                                    if($department[$i]['id'] == $data['idDepartment']){
                                                        echo "<option value={$department[$i]['id']} selected>{$department[$i]['departmentName']}</option>";
                                                    }
                                                    else{
                                                        echo "<option value={$department[$i]['id']}>{$department[$i]['departmentName']}</option>";
                                                    }
                                                    $i += 1;
                                                }
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Chức vụ</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <select name='position' id="employee_position" class="information__container-right__content-list-field__element-value" onchange="checkInvalidValue(id);">
                                            <option value="Nhân viên" selected>Nhân viên</option>
                                            <option value="Trưởng phòng">Trưởng Phòng</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Ngày sinh</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <?php
                                            $dayOfBirth = date('yy-m-d',strtotime($data["dayOfBirth"]));
                                            echo "<input type='date' name='dayOfBirth' id='employee_dayOfBirth' class='information__container-right__content-list-field__element-value' value='{$dayOfBirth}' onchange='checkInvalidValue(id);'></input>";
                                        ?>
                                        
                                    </div>
                                </div>
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Giới tính</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <select name='gender' id="employee_gender" class="information__container-right__content-list-field__element-value" onchange="checkInvalidValue(id);">
                                            <?php
                                                if(strcmp($data["gender"], "Nam") == 0)
                                                    echo "<option value='Nam' selected>Nam</option>";
                                                else
                                                    echo "<option value='Nam'>Nam</option>";

                                                if(strcmp($data["gender"], "Nữ") == 0)
                                                    echo "<option value='Nữ' selected>Nữ</option>";
                                                else
                                                    echo "<option value='Nữ'>Nữ</option>";
                                            ?>
                                            
                                            
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="padding-bottom: 10px;border-bottom: 5px solid var(--angle-color);">
                            <div class="information__container-right__content-list">
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Email</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <?php
                                            echo "<input type='text' name='email' id='employee_email' class='information__container-right__content-list-field__element-value' value='{$data["email"]}' onchange='checkInvalidValue(id);'></input>";
                                        ?>
                                        
                                    </div>
                                </div>
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Số điện thoại</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <?php
                                            echo "<input type='text' name='phoneNumber' id='employee_phone' class='information__container-right__content-list-field__element-value' value='{$data["phoneNumber"]}' onchange='checkInvalidValue(id);'></input>";
                                        ?>
                                        
                                    </div>
                                </div>
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Địa chỉ</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <?php
                                            echo "<input type='text' name='address' id='employee_address' class='information__container-right__content-list-field__element-value' value='{$data["address"]}' onchange='checkInvalidValue(id);'></input>";
                                        ?>
                                        
                                    </div>
                                </div>
                                <div class="information__container-right__content-list-field">
                                    <div class="information__container-right__content-list-field__element">
                                        <span class="information__container-right__content-list-field__element-label">Tình trạng hôn nhân</span>
                                    </div>
                                    <div class="information__container-right__content-list-field__element">
                                        <select name='maritalStatus' id="employee_maritalStatus" class="information__container-right__content-list-field__element-value" onchange="checkInvalidValue(id);">
                                            <?php
                                                if(strcmp($data["maritalStatus"], "Độc thân") == 0)
                                                    echo "<option value='Độc thân' selected>Độc thân</option>";
                                                else
                                                    echo "<option value='Độc thân'>Độc thân</option>";
                                                
                                                if(strcmp($data["maritalStatus"], "Đã kết hôn") == 0)
                                                    echo "<option value='Đã kết hôn' selected>Đã kết hôn</option>";
                                                else
                                                    echo "<option value='Đã kết hôn'>Đã kết hôn</option>";
                                            ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                <form>
                
            </div>

            <div class="row">
                <div class="information__container-right__title">
                    <div class="row information__container-right__title-element">
                        <div class="col-8 information__container-right__title-left">
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__name">Thông tin quản lý</span>
                            </div>
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__description">Thông tin cơ bản người quản lý</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="information__container-right__content">
                    <div class="row" style="padding-bottom: 10px;">
                        <div class="information__container-right__content-list">
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Mã nhân viên</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <?php
                                        echo "<span class='information__container-right__content-list-field__element-value'>{$data["manager_idEmployee"]}</span>";
                                    ?>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Họ</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <?php
                                        echo "<span class='information__container-right__content-list-field__element-value'>{$data["manager_firstname"]}</span>";
                                    ?>
                                    
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Tên</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <?php
                                        echo "<span class='information__container-right__content-list-field__element-value'>{$data["manager_lastname"]}</span>";
                                    ?>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Giới tính</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <?php
                                        echo "<span class='information__container-right__content-list-field__element-value'>{$data["manager_gender"]}</span>";
                                    ?>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="padding-bottom: 10px;">
                        <div class="information__container-right__content-list">
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Phòng ban</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <?php
                                        echo "<span class='information__container-right__content-list-field__element-value'>{$data["manager_departmentName"]}</span>";
                                    ?>
                                    
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Chức vụ</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <?php
                                        echo "<span class='information__container-right__content-list-field__element-value'>{$data["manager_position"]}</span>";
                                    ?>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Email</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <?php
                                        echo "<span class='information__container-right__content-list-field__element-value'>{$data["manager_email"]}</span>";
                                    ?>
                                </div>
                            </div>
                            <div class="information__container-right__content-list-field">
                                <div class="information__container-right__content-list-field__element">
                                    <span class="information__container-right__content-list-field__element-label">Số điện thoại</span>
                                </div>
                                <div class="information__container-right__content-list-field__element">
                                    <?php
                                        echo "<span class='information__container-right__content-list-field__element-value'>{$data["manager_phoneNumber"]}</span>";
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require("js/employee_information.phtml"); ?>