<div class="row requestA">
    <p class="requestA__functionName">Hoạt động của công ty</p>
    <div class="requestA_formName">
        <p class="requestA__formName--status">Danh sách các hoạt động</p>
        <form class="requestA-info__search d-flex" action="index.php" method = "POST">
            <input class="requestA-info_search_form form-control me-2" type="text" placeholder="Nhập hoạt động cần tìm" 
            name = "activityName">
            <button type="submit" class="requestA-info_search__btn btn btn-dark"><i class="requestA-info_search__icon fas fa-search"></i></button>
            <input type="hidden" name="action" value = "searchA"/>
        </form>
    </div>
    <?php
        foreach ($dataAllRequest as $item)  {
            $time = strtotime($item->activityDeadline);
            $item->activityDeadline = date('d-m-Y',$time);
            print"
                <form action='index.php?action=registerA&idActivity={$item->id}' method = 'POST'>
                    <div class='requestA__formItems--status'>
                        <div class='row'>
                            <div class='col-9'>
                                <span class='requestA__formItemsName'>
                                    Tên hoạt động: {$item->activityName}
                                </span>    
                                <span class='requestA__formItemsDescription'>
                                    Mô tả: {$item->activityDescription}
                                </span>   
                                <span class='requestA__formItemsDeadline'>
                                    Hạn chót: {$item->activityDeadline}
                                </span>     
                            </div>
                            <div class='col-3'>
                                <button type='submit' name = 'activity' value = 'Đăng ký'  onclick='RegisterMessageA()' class='requestA_submit-btn btn btn-success'>Đăng ký</button>
                                <button type='submit' name = 'activity' formaction='index.php?action=followA&idActivity={$item->id}' value = 'Theo dõi' onclick='FollowMessageA()' class='requestA_submit-btn btn btn-success'>Theo dõi</button>
                            </div>
                        </div>
                    </div>
                </form>
            
            ";
        }
    ?>
</div>

<?php require("js/employee_A.phtml"); ?>