<div class="ApprovalITManager">
    <p class="ApprovalITManager__functionName">Xét duyệt thiết bị</p>
    <div class="row ApprovalITManager__formItems">
        <div class="col-9 ApprovalITManager__formItems--list">
            <p class="ApprovalITManager__formName">Danh sách xét duyệt</p>
            <div class="ApprovalITManager__formItems--header">
                <a href="#" class="ApprovalITManager_All-btn">Tất cả</a>
                <a href="#" class="ApprovalITManager_All-btn">Đang chờ duyệt</a>
                <a href="#" class="ApprovalITManager_All-btn">Tạm duyệt</a>
                <a href="#" class="ApprovalITManager_All-btn">Từ chối</a>
            </div>
            <table class="ApprovalITManager__formItems--table">
                <thead>
                    <tr class="ApprovalITManager__formItems--header--tr">
                        <td class="ApprovalITManager__formItems--header--td">Tên</td>
                        <td class="ApprovalITManager__formItems--header--td">Loại</td>
                        <td class="ApprovalITManager__formItems--header--td">Ghi chú</td>
                        <td class="ApprovalITManager__formItems--header--td">Lý do</td>
                        <td class="ApprovalITManager__formItems--header--td">Ngày gửi</td>
                        <td class="ApprovalITManager__formItems--header--td">Trạng thái</td>
                    </tr>
                </thead>
                <tbody>
                    <tr class="ApprovalITManager__formItems--body--tr">
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Máy tính xách tay Casio</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Phần cứng</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Casio fx-1975 PLUS</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Lười tính tay</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">20/02/2023</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Đang chờ duyệt</a>
                        </td>
                    </tr>
                    <tr class="ApprovalITManager__formItems--body--tr">
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Máy tính xách tay Casio</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Phần cứng</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Casio fx-1975 PLUS</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Lười tính tay</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">20/02/2023</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Tạm duyệt</a>
                        </td>
                    </tr>
                    <tr class="ApprovalITManager__formItems--body--tr">
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Máy tính xách tay Casio</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Phần cứng</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Casio fx-1975 PLUS</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Lười tính tay</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">20/02/2023</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Tạm duyệt</a>
                        </td>
                    </tr>
                    <tr class="ApprovalITManager__formItems--body--tr">
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Máy tính xách tay Casio</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Phần cứng</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Casio fx-1975 PLUS</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Lười tính tay</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">20/02/2023</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Tạm duyệt</a>
                        </td>
                    </tr>
                    <tr class="ApprovalITManager__formItems--body--tr">
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Máy tính xách tay Casio</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Phần cứng</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Casio fx-1975 PLUS</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Lười tính tay</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">20/02/2023</a>
                        </td>
                        <td class="ApprovalITManager__formItems--body--td">
                            <a href="#" class="ApprovalITManager__formItems--body--a">Đang chờ duyệt</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-3 ApprovalITManager__formDevices--list">
            <p class="ApprovalITManager__formName">Danh sách thiết bị</p>
            <table class="ApprovalITManager__formDevices--table">
                <thead>
                    <tr class="ApprovalITManager__formDevices--header--tr">
                        <td class="ApprovalITManager__formDevices--header--td">Tên</td>
                        <td class="ApprovalITManager__formDevices--header--td">Số lượng</td>
                    </tr>
                </thead>
                <tbody>
                    <tr class="ApprovalITManager__formDevices--body--tr">
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">Máy tính xách tay Casio</a>
                        </td>
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">20</a>
                        </td>
                    </tr>
                    <tr class="ApprovalITManager__formDevices--body--tr">
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">Máy tính xách tay Casio</a>
                        </td>
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">20</a>
                        </td>
                    </tr>
                    <tr class="ApprovalITManager__formDevices--body--tr">
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">Máy tính xách tay Casio</a>
                        </td>
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">20</a>
                        </td>
                    </tr>
                    <tr class="ApprovalITManager__formDevices--body--tr">
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">Máy tính xách tay Casio</a>
                        </td>
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">20</a>
                        </td>
                    </tr>
                    <tr class="ApprovalITManager__formDevices--body--tr">
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">Máy tính xách tay Casio</a>
                        </td>
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">20</a>
                        </td>
                    </tr>
                    <tr class="ApprovalITManager__formDevices--body--tr">
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">Máy tính xách tay Casio</a>
                        </td>
                        <td class="ApprovalITManager__formDevices--body--td">
                            <a href="#" class="ApprovalITManager__formDevices--body--a">20</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>