<div class="information__header">
    <div class="row">
        <div class="information__header_nav">
            <a class="information__header-nav-item">
                <i class="information__header-nav-item-icon fa-solid fa-angle-right"></i>
                <p class="information__header-nav-item-name">Quản lý công việc</p>
            </a>
        </div>
    </div>
</div>
<div class="information__container">
    <div class="row">
        <div class="information__container-right">
            <div class="row" style="padding-bottom: 10px;">
                <div class="information__container-right__title col-8">
                    <div class="row information__container-right__title-element">
                        <div class="col-8 information__container-right__title-left">
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__name">Danh sách công việc</span>
                            </div>
                            <div class="information__container-right__title-left-element">
                                <span class="information__container-right__title-left-element__description">Danh sách các công việc và trạng thái</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="information__container-right__filter col-4">
                    <div class="row">
                        <div class="information__container-right__filter-list">
                            <div class="information__container-right__filter-list-item">
                                <select class="information__container-right__filter-list-item__element" onchange="filterStatus(this);">
                                    <?php
                                        $idEmployee = $_REQUEST['idEmployee'];
                                        $status = $_REQUEST['status'];

                                        if(strcmp($status, "all") == 0){
                                            echo "<option value='{$idEmployee}&page=1&status=all' selected>Tất cả trạng thái</option>";
                                        }
                                        else{
                                            echo "<option value='{$idEmployee}&page=1&status=all'>Tất cả trạng thái</option>";
                                        }

                                        if(strcmp($status, "out") == 0){
                                            echo "<option value='{$idEmployee}&page=1&status=out' selected>Quá hạn</option>";
                                        }
                                        else{
                                            echo "<option value='{$idEmployee}&page=1&status=out'>Quá hạn</option>";
                                        }

                                        if(strcmp($status, "complete") == 0){
                                            echo "<option value='{$idEmployee}&page=1&status=complete' selected>Hoàn thành</option>";
                                        }
                                        else{
                                            echo "<option value='{$idEmployee}&page=1&status=complete'>Hoàn thành</option>";
                                        }

                                        if(strcmp($status, "doing") == 0){
                                            echo "<option value='{$idEmployee}&page=1&status=doing' selected>Đang thực hiện</option>";
                                        }
                                        else{
                                            echo "<option value='{$idEmployee}&page=1&status=doing'>Đang thực hiện</option>";
                                        }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="information__container-right__content">
                    <div class="row">
                        <div class="information__container-right__content-list">
                            <div class="information__container-right__content-list-title">
                                <div class="information__container-right__content-list-title__work">
                                    <span>CÔNG VIỆC</span>
                                </div>
                                <div class="information__container-right__content-list-title__deadline">
                                    <span>DEADLINE</span>
                                </div>
                                <div class="information__container-right__content-list-title__project">
                                    <span>DỰ ÁN</span>
                                </div>
                                <div class="information__container-right__content-list-title__status">
                                    <span>TRẠNG THÁI</span>
                                </div>
                            </div>
                            <?php
                                if(isset($data)){
                                    $self = $_SERVER['PHP_SELF'];
                                    $currentPage = 1;
                                    if (isset($_REQUEST["page"]))
                                        $currentPage = $_REQUEST["page"];
                                    $n = count($data);
                                    $i = 0;
                                    while($i < $n){
                                        $deadline = date('d-m-Y',strtotime($data[$i]["deadline"]));
                                        echo "<div class='information__container-right__content-list-item'>
                                        <a class='information__container-right__content-list-item-link'>
                                            <div class='information__container-right__content-list-item-link-job'>
                                                <span class='information__container-right__content-list-item-link-job-value'>{$data[$i]["taskName"]}</span>
                                            </div>
                                            <div class='information__container-right__content-list-item-link-deadline'>
                                                <span class='information__container-right__content-list-item-link-deadline-value'>{$deadline}</span>
                                            </div>
                                            <div class='information__container-right__content-list-item-link-project'>
                                                <span class='information__container-right__content-list-item-link-project-value'>{$data[$i]["projectName"]}</span>
                                            </div>
                                            <div class='information__container-right__content-list-item-link-status'>
                                                <span class='information__container-right__content-list-item-link-status-value'>{$data[$i]["status"]}</span>
                                            </div>
                                        </a>
                                    </div>";
                                        $i += 1;
                                    }
                                }
                                
                            ?>
                        </div>
                        <div class="information__container-right__content-list-paging">
                            <div class="information__container-right__content-list-paging-element">
                                <?php
                                    if ($currentPage > 1)
                                    {
                                        $page = $currentPage - 1;
                                        $prev = "<a class='paging-data' href='$self?action=managertask&idEmployee=$idEmployee&page=$page&status=$status'><</a>";
                                    }
                                    else
                                    {
                                        $prev = "<a class='paging-data' href='$self?action=managertask&idEmployee=$idEmployee&page=1&status=$status'><</a>";
                                    }


                                    $page = $currentPage + 1;
                                    $next = "     <a class='paging-data' href='$self?action=managertask&idEmployee=$idEmployee&page=$page&status=$status'>></a>";

                                    echo $prev.$currentPage.$next;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php require("js/manager_tasks.phtml"); ?>
