<div class="president_formDR">
    <p class="president_formDR__functionName">Xét duyệt thiết bị</p>
    <div class="row president_formDR__form">
        <div class="col-6 president_formDR__form--info">
            <span class="row president_formDR__formTitle">Máy tính xách tay Casio</span>
            <div class="president_formDR__formStatus">
                <span class="president_formDR__formStatus--name">Trạng thái:</span>
                <span class="president_formDR__formStatus--status">Tạm duyệt</span>
            </div>
            <div class="president_formDR__formRequestSuggest">
                <span class="president_formDR__formRequestSuggest--name">Thông tin đề xuất</span>
            </div>
            <div class="president_formDR__formRequestInfo">
                <div class="row president_formDR__formRequestInfo--items">
                    <i class="col-1 president_formDR__formRequestInfo--items__logo fa-solid fa-id-badge"></i>
                    <span class="col-5 president_formDR__formRequestInfo--items--info1">Mã đề xuất</span>
                    <span class="col-6 president_formDR__formRequestInfo--items--info2">123ABC</span>
                </div>
                <div class="row president_formDR__formRequestInfo--items">
                    <i class="col-1 president_formDR__formRequestInfo--items__logo fa-solid fa-user"></i>
                    <span class="col-5 president_formDR__formRequestInfo--items--info1">Người tạo</span>
                    <span class="col-6 president_formDR__formRequestInfo--items--info2">Trần Văn B</span>
                </div>
                <div class="row president_formDR__formRequestInfo--items">
                    <i class="col-1 president_formDR__formRequestInfo--items__logo fa-solid fa-user"></i>
                    <span class="col-5 president_formDR__formRequestInfo--items--info1">Người xét duyệt</span>
                    <span class="col-6 president_formDR__formRequestInfo--items--info2">Trần Văn C</span>
                </div>
                <div class="row president_formDR__formRequestInfo--items">
                    <i class="col-1 president_formDR__formRequestInfo--items__logo fa-solid fa-calendar"></i>
                    <span class="col-5 president_formDR__formRequestInfo--items--info1">Loại thiết bị</span>
                    <span class="col-6 president_formDR__formRequestInfo--items--info2">Phần cứng</span>
                </div>
                <div class="row president_formDR__formRequestInfo--items">
                    <i class="col-1 president_formDR__formRequestInfo--items__logo fa-solid fa-calendar-days"></i>
                    <span class="col-5 president_formDR__formRequestInfo--items--info1">Ngày gửi</span>
                    <span class="col-6 president_formDR__formRequestInfo--items--info2">20/02/2023</span>
                </div>
            </div>
            <div class="president_formDR__formRequestSuggest">
                <span class="president_formDR__formRequestSuggest--name">Thông tin chi tiết</span>
            </div>
            <div class="president_formDR__formRequestInfo">
                <div class="row president_formDR__formRequestInfo--items">
                    <i class="fa-solid fa-note"></i>
                    <i class="col-1 president_formDR__formRequestInfo--items__logo fa-solid fa-clipboard"></i>
                    <span class="col-5 president_formDR__formRequestInfo--items--info1">Ghi chú</span>
                    <span class="col-6 president_formDR__formRequestInfo--items--info2">Casio 123456</span>

                </div>
                <div class="row president_formDR__formRequestInfo--items">
                    <i class="col-1 president_formDR__formRequestInfo--items__logo fa-solid fa-comment-dots"></i>
                    <span class="col-5 president_formDR__formRequestInfo--items--info1">Lý do</span>
                    <p class="col-6 president_formDR__formRequestInfo--items--info2">Lười tính tay</p>
                </div>

            </div>

        </div>
        <div class="col-6 president_formDR__form--contact">
            <span class="president_formDR__formReasonName">Lý do từ chối yêu cầu (Nếu có)</span>
            <textarea class="president_formDR__formInput"></textarea>
            <div class="president_formDR_btn">
                <button type="submit" class="president_formDR_submit-btn btn btn-success">Chấp nhận</button>
                <button type="submit" class="president_formDR_cancel-btn btn btn-danger">Từ chối</button>
            </div>

        </div>
    </div>
</div>