<div class="President_DR">
    <p class="President_DR__functionName">Xét duyệt thiết bị</p>
    <div class="row President_DR__formItems">
        <p class="President_DR__formName">Danh sách xét duyệt</p>
        <?php
                $successP = 'Thành công';
                $tempP = 'Tạm duyệt';
                $defuseP = 'Từ chối';
                print "
                <div class='President_DR__formItems--header'>
                    <a href='index.php?action=listALLDR_president' class='President_DR_All-btn'>Tất cả</a>
                    <a href='index.php?action=President_DR&requestStatus={$tempP}' class='President_DR_All-btn'>Tạm duyệt</a>
                    <a href='index.php?action=President_DR&requestStatus={$successP}' class='President_DR_All-btn'>Thành công</a>
                    <a href='index.php?action=President_DR&requestStatus={$defuseP}' class='President_DR_All-btn'>Từ chối</a>
                </div>";
        ?>
        <table class="President_DR__formItems--table">
            <thead>
                <tr class="President_DR__formItems--header--tr">
                    <td class="President_DR__formItems--header--td">Thiết bị/Phần mềm</td>
                    <td class="President_DR__formItems--header--td">Ghi chú</td>
                    <td class="President_DR__formItems--header--td">Lý do</td>
                    <td class="President_DR__formItems--header--td">Ngày gửi</td>
                    <td class="President_DR__formItems--header--td">Trạng thái</td>
                </tr>
            </thead>
            <?php
                foreach ($dataAllRequest as $item)  {
                    if ($item->requestStatus == 'Đang chờ duyệt') {
                        continue;
                    }
                    else if (is_null($item->requestITRejectReason) != 1 && is_null($item->idITManager) != 1) {
                        continue;
                    }
                    $time = strtotime($item->requestDate);
                    $item->requestDate = date('d-m-Y',$time);
                    print "
                    <tbody>
                        <tr class='President_DR__formItems--body--tr'>
                                <td class='President_DR__formItems--body--td'>
                                    <a href='index.php?action=listpresident_formDR&id={$item->id}' class='President_DR__formItems--body--a'>
                                        {$item->requestName}
                                    </a>
                                </td>
                                <td class='President_DR__formItems--body--td'>
                                    <a href='index.php?action=listpresident_formDR&id={$item->id}' class='President_DR__formItems--body--a'>
                                        {$item->noteRequest}
                                    </a>   
                                </td>
                                <td class='President_DR__formItems--body--td'>
                                    <a href='index.php?action=listpresident_formDR&id={$item->id}' class='President_DR__formItems--body--a'>
                                        {$item->reason}
                                    </a>
                                </td>
                                <td class='President_DR__formItems--body--td'>
                                    <a href='index.php?action=listpresident_formDR&id={$item->id}' class='President_DR__formItems--body--a'>
                                        {$item->requestDate}
                                    </a>
                                </td>
                                <td class='President_DR__formItems--body--td'>
                                    <a href='index.php?action=listpresident_formDR&id={$item->id}' class='President_DR__formItems--body--a'>
                                        {$item->requestStatus}
                                    </a>
                                </td>
                        </tr>
                    </tbody>";
                }
                ?>
        </table>

    </div>

</div>