<div class="President_DR">
    <p class="President_DR__functionName">Xét duyệt thiết bị</p>
    <div class="row President_DR__formItems">
        <p class="President_DR__formName">Danh sách xét duyệt</p>
        <div class="President_DR__formItems--header">
            <a href="#" class="President_DR_All-btn">Tất cả</a>
            <a href="#" class="President_DR_All-btn">Tạm duyệt</a>
            <a href="#" class="President_DR_All-btn">Thành công</a>
            <a href="#" class="President_DR_All-btn">Từ chối</a>
        </div>
        <table class="President_DR__formItems--table">
            <thead>
                <tr class="President_DR__formItems--header--tr">
                    <td class="President_DR__formItems--header--td">Thiết bị/Phần mềm</td>
                    <td class="President_DR__formItems--header--td">Ghi chú</td>
                    <td class="President_DR__formItems--header--td">Lý do</td>
                    <td class="President_DR__formItems--header--td">Ngày gửi</td>
                    <td class="President_DR__formItems--header--td">Người xét duyệt</td>
                    <td class="President_DR__formItems--header--td">Trạng thái</td>
                </tr>
            </thead>
            <tbody>
                <tr class="President_DR__formItems--body--tr">
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Máy tính xách tay Casio</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Casio fx-1975 PLUS</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Lười tính tay</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">20/02/2023</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">N.V.Anh</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Từ chối</a>
                    </td>
                </tr>
                <tr class="President_DR__formItems--body--tr">
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Máy tính xách tay Casio</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Casio fx-1975 PLUS</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Lười tính tay</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">20/02/2023</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">N.V.Anh</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Từ chối</a>
                    </td>
                </tr>
                <tr class="President_DR__formItems--body--tr">
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Máy tính xách tay Casio</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Casio fx-1975 PLUS</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Lười tính tay</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">20/02/2023</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">N.V.Anh</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Tạm duyệt</a>
                    </td>
                </tr>
                <tr class="President_DR__formItems--body--tr">
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Máy tính xách tay Casio</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Casio fx-1975 PLUS</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Lười tính tay</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">20/02/2023</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">N.V.Anh</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Tạm duyệt</a>
                    </td>
                </tr>
                <tr class="President_DR__formItems--body--tr">
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Máy tính xách tay Casio</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Casio fx-1975 PLUS</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Lười tính tay</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">20/02/2023</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">N.V.Anh</a>
                    </td>
                    <td class="President_DR__formItems--body--td">
                        <a href="#" class="President_DR__formItems--body--a">Thành công</a>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>

</div>